// Code generated by MockGen. DO NOT EDIT.
// Source: ../interfaces.go

// Package repository_mocks is a generated GoMock package.
package repository_mocks

import (
	reflect "reflect"
	time "time"

	models "array-assessment/internal/models"
	repositories "array-assessment/internal/repositories"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
	decimal "github.com/shopspring/decimal"
)

// MockAccountRepositoryInterface is a mock of AccountRepositoryInterface interface.
type MockAccountRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockAccountRepositoryInterfaceMockRecorder
}

// MockAccountRepositoryInterfaceMockRecorder is the mock recorder for MockAccountRepositoryInterface.
type MockAccountRepositoryInterfaceMockRecorder struct {
	mock *MockAccountRepositoryInterface
}

// NewMockAccountRepositoryInterface creates a new mock instance.
func NewMockAccountRepositoryInterface(ctrl *gomock.Controller) *MockAccountRepositoryInterface {
	mock := &MockAccountRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockAccountRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccountRepositoryInterface) EXPECT() *MockAccountRepositoryInterfaceMockRecorder {
	return m.recorder
}

// CheckAccountNumberExists mocks base method.
func (m *MockAccountRepositoryInterface) CheckAccountNumberExists(accountNumber string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckAccountNumberExists", accountNumber)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckAccountNumberExists indicates an expected call of CheckAccountNumberExists.
func (mr *MockAccountRepositoryInterfaceMockRecorder) CheckAccountNumberExists(accountNumber interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckAccountNumberExists", reflect.TypeOf((*MockAccountRepositoryInterface)(nil).CheckAccountNumberExists), accountNumber)
}

// Create mocks base method.
func (m *MockAccountRepositoryInterface) Create(account *models.Account) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", account)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockAccountRepositoryInterfaceMockRecorder) Create(account interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAccountRepositoryInterface)(nil).Create), account)
}

// CreateWithTransaction mocks base method.
func (m *MockAccountRepositoryInterface) CreateWithTransaction(account *models.Account, transactions []models.Transaction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWithTransaction", account, transactions)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateWithTransaction indicates an expected call of CreateWithTransaction.
func (mr *MockAccountRepositoryInterfaceMockRecorder) CreateWithTransaction(account, transactions interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWithTransaction", reflect.TypeOf((*MockAccountRepositoryInterface)(nil).CreateWithTransaction), account, transactions)
}

// Delete mocks base method.
func (m *MockAccountRepositoryInterface) Delete(id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockAccountRepositoryInterfaceMockRecorder) Delete(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockAccountRepositoryInterface)(nil).Delete), id)
}

// ExecuteAtomicTransfer mocks base method.
func (m *MockAccountRepositoryInterface) ExecuteAtomicTransfer(fromAccountID, toAccountID uuid.UUID, amount decimal.Decimal, fromDescription, toDescription string) (uuid.UUID, uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteAtomicTransfer", fromAccountID, toAccountID, amount, fromDescription, toDescription)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(uuid.UUID)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ExecuteAtomicTransfer indicates an expected call of ExecuteAtomicTransfer.
func (mr *MockAccountRepositoryInterfaceMockRecorder) ExecuteAtomicTransfer(fromAccountID, toAccountID, amount, fromDescription, toDescription interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteAtomicTransfer", reflect.TypeOf((*MockAccountRepositoryInterface)(nil).ExecuteAtomicTransfer), fromAccountID, toAccountID, amount, fromDescription, toDescription)
}

// ExistsForUser mocks base method.
func (m *MockAccountRepositoryInterface) ExistsForUser(userID uuid.UUID, accountType string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistsForUser", userID, accountType)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistsForUser indicates an expected call of ExistsForUser.
func (mr *MockAccountRepositoryInterfaceMockRecorder) ExistsForUser(userID, accountType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsForUser", reflect.TypeOf((*MockAccountRepositoryInterface)(nil).ExistsForUser), userID, accountType)
}

// GenerateUniqueAccountNumber mocks base method.
func (m *MockAccountRepositoryInterface) GenerateUniqueAccountNumber(accountType string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateUniqueAccountNumber", accountType)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateUniqueAccountNumber indicates an expected call of GenerateUniqueAccountNumber.
func (mr *MockAccountRepositoryInterfaceMockRecorder) GenerateUniqueAccountNumber(accountType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateUniqueAccountNumber", reflect.TypeOf((*MockAccountRepositoryInterface)(nil).GenerateUniqueAccountNumber), accountType)
}

// GetAccountsByStatus mocks base method.
func (m *MockAccountRepositoryInterface) GetAccountsByStatus(status string, offset, limit int) ([]models.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountsByStatus", status, offset, limit)
	ret0, _ := ret[0].([]models.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountsByStatus indicates an expected call of GetAccountsByStatus.
func (mr *MockAccountRepositoryInterfaceMockRecorder) GetAccountsByStatus(status, offset, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountsByStatus", reflect.TypeOf((*MockAccountRepositoryInterface)(nil).GetAccountsByStatus), status, offset, limit)
}

// GetAll mocks base method.
func (m *MockAccountRepositoryInterface) GetAll(offset, limit int) ([]models.Account, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", offset, limit)
	ret0, _ := ret[0].([]models.Account)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetAll indicates an expected call of GetAll.
func (mr *MockAccountRepositoryInterfaceMockRecorder) GetAll(offset, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockAccountRepositoryInterface)(nil).GetAll), offset, limit)
}

// GetAllWithFilters mocks base method.
func (m *MockAccountRepositoryInterface) GetAllWithFilters(filters models.AccountFilters, offset, limit int) ([]models.Account, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllWithFilters", filters, offset, limit)
	ret0, _ := ret[0].([]models.Account)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetAllWithFilters indicates an expected call of GetAllWithFilters.
func (mr *MockAccountRepositoryInterfaceMockRecorder) GetAllWithFilters(filters, offset, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllWithFilters", reflect.TypeOf((*MockAccountRepositoryInterface)(nil).GetAllWithFilters), filters, offset, limit)
}

// GetByAccountNumber mocks base method.
func (m *MockAccountRepositoryInterface) GetByAccountNumber(accountNumber string) (*models.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByAccountNumber", accountNumber)
	ret0, _ := ret[0].(*models.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByAccountNumber indicates an expected call of GetByAccountNumber.
func (mr *MockAccountRepositoryInterfaceMockRecorder) GetByAccountNumber(accountNumber interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByAccountNumber", reflect.TypeOf((*MockAccountRepositoryInterface)(nil).GetByAccountNumber), accountNumber)
}

// GetByID mocks base method.
func (m *MockAccountRepositoryInterface) GetByID(id uuid.UUID) (*models.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", id)
	ret0, _ := ret[0].(*models.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockAccountRepositoryInterfaceMockRecorder) GetByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockAccountRepositoryInterface)(nil).GetByID), id)
}

// GetByUserID mocks base method.
func (m *MockAccountRepositoryInterface) GetByUserID(userID uuid.UUID) ([]models.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserID", userID)
	ret0, _ := ret[0].([]models.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserID indicates an expected call of GetByUserID.
func (mr *MockAccountRepositoryInterfaceMockRecorder) GetByUserID(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserID", reflect.TypeOf((*MockAccountRepositoryInterface)(nil).GetByUserID), userID)
}

// GetByUserIDAndType mocks base method.
func (m *MockAccountRepositoryInterface) GetByUserIDAndType(userID uuid.UUID, accountType string) ([]models.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserIDAndType", userID, accountType)
	ret0, _ := ret[0].([]models.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserIDAndType indicates an expected call of GetByUserIDAndType.
func (mr *MockAccountRepositoryInterfaceMockRecorder) GetByUserIDAndType(userID, accountType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserIDAndType", reflect.TypeOf((*MockAccountRepositoryInterface)(nil).GetByUserIDAndType), userID, accountType)
}

// GetByUserIDExcludingStatus mocks base method.
func (m *MockAccountRepositoryInterface) GetByUserIDExcludingStatus(userID uuid.UUID, excludeStatus string) ([]*models.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserIDExcludingStatus", userID, excludeStatus)
	ret0, _ := ret[0].([]*models.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserIDExcludingStatus indicates an expected call of GetByUserIDExcludingStatus.
func (mr *MockAccountRepositoryInterfaceMockRecorder) GetByUserIDExcludingStatus(userID, excludeStatus interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserIDExcludingStatus", reflect.TypeOf((*MockAccountRepositoryInterface)(nil).GetByUserIDExcludingStatus), userID, excludeStatus)
}

// GetTotalBalanceByUserID mocks base method.
func (m *MockAccountRepositoryInterface) GetTotalBalanceByUserID(userID uuid.UUID) (decimal.Decimal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTotalBalanceByUserID", userID)
	ret0, _ := ret[0].(decimal.Decimal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTotalBalanceByUserID indicates an expected call of GetTotalBalanceByUserID.
func (mr *MockAccountRepositoryInterfaceMockRecorder) GetTotalBalanceByUserID(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTotalBalanceByUserID", reflect.TypeOf((*MockAccountRepositoryInterface)(nil).GetTotalBalanceByUserID), userID)
}

// SoftDeleteByUserID mocks base method.
func (m *MockAccountRepositoryInterface) SoftDeleteByUserID(userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDeleteByUserID", userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SoftDeleteByUserID indicates an expected call of SoftDeleteByUserID.
func (mr *MockAccountRepositoryInterfaceMockRecorder) SoftDeleteByUserID(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDeleteByUserID", reflect.TypeOf((*MockAccountRepositoryInterface)(nil).SoftDeleteByUserID), userID)
}

// Update mocks base method.
func (m *MockAccountRepositoryInterface) Update(account *models.Account) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", account)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockAccountRepositoryInterfaceMockRecorder) Update(account interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockAccountRepositoryInterface)(nil).Update), account)
}

// UpdateBalance mocks base method.
func (m *MockAccountRepositoryInterface) UpdateBalance(accountID uuid.UUID, amount decimal.Decimal, transactionType string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBalance", accountID, amount, transactionType)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBalance indicates an expected call of UpdateBalance.
func (mr *MockAccountRepositoryInterfaceMockRecorder) UpdateBalance(accountID, amount, transactionType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBalance", reflect.TypeOf((*MockAccountRepositoryInterface)(nil).UpdateBalance), accountID, amount, transactionType)
}

// UpdateOwnership mocks base method.
func (m *MockAccountRepositoryInterface) UpdateOwnership(accountID, newUserID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOwnership", accountID, newUserID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateOwnership indicates an expected call of UpdateOwnership.
func (mr *MockAccountRepositoryInterfaceMockRecorder) UpdateOwnership(accountID, newUserID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOwnership", reflect.TypeOf((*MockAccountRepositoryInterface)(nil).UpdateOwnership), accountID, newUserID)
}

// MockTransactionRepositoryInterface is a mock of TransactionRepositoryInterface interface.
type MockTransactionRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockTransactionRepositoryInterfaceMockRecorder
}

// MockTransactionRepositoryInterfaceMockRecorder is the mock recorder for MockTransactionRepositoryInterface.
type MockTransactionRepositoryInterfaceMockRecorder struct {
	mock *MockTransactionRepositoryInterface
}

// NewMockTransactionRepositoryInterface creates a new mock instance.
func NewMockTransactionRepositoryInterface(ctrl *gomock.Controller) *MockTransactionRepositoryInterface {
	mock := &MockTransactionRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockTransactionRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransactionRepositoryInterface) EXPECT() *MockTransactionRepositoryInterfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockTransactionRepositoryInterface) Create(transaction *models.Transaction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", transaction)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockTransactionRepositoryInterfaceMockRecorder) Create(transaction interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTransactionRepositoryInterface)(nil).Create), transaction)
}

// CreateBatch mocks base method.
func (m *MockTransactionRepositoryInterface) CreateBatch(transactions []models.Transaction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBatch", transactions)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateBatch indicates an expected call of CreateBatch.
func (mr *MockTransactionRepositoryInterfaceMockRecorder) CreateBatch(transactions interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBatch", reflect.TypeOf((*MockTransactionRepositoryInterface)(nil).CreateBatch), transactions)
}

// GetByAccountID mocks base method.
func (m *MockTransactionRepositoryInterface) GetByAccountID(accountID uuid.UUID, offset, limit int) ([]models.Transaction, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByAccountID", accountID, offset, limit)
	ret0, _ := ret[0].([]models.Transaction)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetByAccountID indicates an expected call of GetByAccountID.
func (mr *MockTransactionRepositoryInterfaceMockRecorder) GetByAccountID(accountID, offset, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByAccountID", reflect.TypeOf((*MockTransactionRepositoryInterface)(nil).GetByAccountID), accountID, offset, limit)
}

// GetByCategory mocks base method.
func (m *MockTransactionRepositoryInterface) GetByCategory(accountID uuid.UUID, category string, offset, limit int) ([]models.Transaction, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByCategory", accountID, category, offset, limit)
	ret0, _ := ret[0].([]models.Transaction)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetByCategory indicates an expected call of GetByCategory.
func (mr *MockTransactionRepositoryInterfaceMockRecorder) GetByCategory(accountID, category, offset, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByCategory", reflect.TypeOf((*MockTransactionRepositoryInterface)(nil).GetByCategory), accountID, category, offset, limit)
}

// GetByDateRange mocks base method.
func (m *MockTransactionRepositoryInterface) GetByDateRange(accountID uuid.UUID, startDate, endDate time.Time) ([]models.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByDateRange", accountID, startDate, endDate)
	ret0, _ := ret[0].([]models.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByDateRange indicates an expected call of GetByDateRange.
func (mr *MockTransactionRepositoryInterfaceMockRecorder) GetByDateRange(accountID, startDate, endDate interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByDateRange", reflect.TypeOf((*MockTransactionRepositoryInterface)(nil).GetByDateRange), accountID, startDate, endDate)
}

// GetByID mocks base method.
func (m *MockTransactionRepositoryInterface) GetByID(id uuid.UUID) (*models.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", id)
	ret0, _ := ret[0].(*models.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockTransactionRepositoryInterfaceMockRecorder) GetByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockTransactionRepositoryInterface)(nil).GetByID), id)
}

// GetByReference mocks base method.
func (m *MockTransactionRepositoryInterface) GetByReference(reference string) (*models.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByReference", reference)
	ret0, _ := ret[0].(*models.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByReference indicates an expected call of GetByReference.
func (mr *MockTransactionRepositoryInterfaceMockRecorder) GetByReference(reference interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByReference", reflect.TypeOf((*MockTransactionRepositoryInterface)(nil).GetByReference), reference)
}

// GetCategorySummary mocks base method.
func (m *MockTransactionRepositoryInterface) GetCategorySummary(accountID uuid.UUID, startDate, endDate time.Time) ([]models.CategorySummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCategorySummary", accountID, startDate, endDate)
	ret0, _ := ret[0].([]models.CategorySummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCategorySummary indicates an expected call of GetCategorySummary.
func (mr *MockTransactionRepositoryInterfaceMockRecorder) GetCategorySummary(accountID, startDate, endDate interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCategorySummary", reflect.TypeOf((*MockTransactionRepositoryInterface)(nil).GetCategorySummary), accountID, startDate, endDate)
}

// GetExpiredPendingTransactions mocks base method.
func (m *MockTransactionRepositoryInterface) GetExpiredPendingTransactions(limit int) ([]models.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExpiredPendingTransactions", limit)
	ret0, _ := ret[0].([]models.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetExpiredPendingTransactions indicates an expected call of GetExpiredPendingTransactions.
func (mr *MockTransactionRepositoryInterfaceMockRecorder) GetExpiredPendingTransactions(limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExpiredPendingTransactions", reflect.TypeOf((*MockTransactionRepositoryInterface)(nil).GetExpiredPendingTransactions), limit)
}

// GetPendingTransactions mocks base method.
func (m *MockTransactionRepositoryInterface) GetPendingTransactions(offset, limit int) ([]models.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPendingTransactions", offset, limit)
	ret0, _ := ret[0].([]models.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPendingTransactions indicates an expected call of GetPendingTransactions.
func (mr *MockTransactionRepositoryInterfaceMockRecorder) GetPendingTransactions(offset, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPendingTransactions", reflect.TypeOf((*MockTransactionRepositoryInterface)(nil).GetPendingTransactions), offset, limit)
}

// GetRecentByAccountID mocks base method.
func (m *MockTransactionRepositoryInterface) GetRecentByAccountID(accountID uuid.UUID, limit int) ([]models.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRecentByAccountID", accountID, limit)
	ret0, _ := ret[0].([]models.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRecentByAccountID indicates an expected call of GetRecentByAccountID.
func (mr *MockTransactionRepositoryInterfaceMockRecorder) GetRecentByAccountID(accountID, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRecentByAccountID", reflect.TypeOf((*MockTransactionRepositoryInterface)(nil).GetRecentByAccountID), accountID, limit)
}

// GetTotalsByAccountID mocks base method.
func (m *MockTransactionRepositoryInterface) GetTotalsByAccountID(accountID uuid.UUID) (int64, int64, string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTotalsByAccountID", accountID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(string)
	ret3, _ := ret[3].(string)
	ret4, _ := ret[4].(error)
	return ret0, ret1, ret2, ret3, ret4
}

// GetTotalsByAccountID indicates an expected call of GetTotalsByAccountID.
func (mr *MockTransactionRepositoryInterfaceMockRecorder) GetTotalsByAccountID(accountID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTotalsByAccountID", reflect.TypeOf((*MockTransactionRepositoryInterface)(nil).GetTotalsByAccountID), accountID)
}

// GetWithFilters mocks base method.
func (m *MockTransactionRepositoryInterface) GetWithFilters(filters models.TransactionFilters) ([]models.Transaction, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWithFilters", filters)
	ret0, _ := ret[0].([]models.Transaction)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetWithFilters indicates an expected call of GetWithFilters.
func (mr *MockTransactionRepositoryInterfaceMockRecorder) GetWithFilters(filters interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWithFilters", reflect.TypeOf((*MockTransactionRepositoryInterface)(nil).GetWithFilters), filters)
}

// UpdateStatus mocks base method.
func (m *MockTransactionRepositoryInterface) UpdateStatus(id uuid.UUID, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockTransactionRepositoryInterfaceMockRecorder) UpdateStatus(id, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockTransactionRepositoryInterface)(nil).UpdateStatus), id, status)
}

// UpdateWithOptimisticLock mocks base method.
func (m *MockTransactionRepositoryInterface) UpdateWithOptimisticLock(transaction *models.Transaction, expectedVersion int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateWithOptimisticLock", transaction, expectedVersion)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateWithOptimisticLock indicates an expected call of UpdateWithOptimisticLock.
func (mr *MockTransactionRepositoryInterfaceMockRecorder) UpdateWithOptimisticLock(transaction, expectedVersion interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateWithOptimisticLock", reflect.TypeOf((*MockTransactionRepositoryInterface)(nil).UpdateWithOptimisticLock), transaction, expectedVersion)
}

// MockUserRepositoryInterface is a mock of UserRepositoryInterface interface.
type MockUserRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryInterfaceMockRecorder
}

// MockUserRepositoryInterfaceMockRecorder is the mock recorder for MockUserRepositoryInterface.
type MockUserRepositoryInterfaceMockRecorder struct {
	mock *MockUserRepositoryInterface
}

// NewMockUserRepositoryInterface creates a new mock instance.
func NewMockUserRepositoryInterface(ctrl *gomock.Controller) *MockUserRepositoryInterface {
	mock := &MockUserRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepositoryInterface) EXPECT() *MockUserRepositoryInterfaceMockRecorder {
	return m.recorder
}

// CountAccountsByUserID mocks base method.
func (m *MockUserRepositoryInterface) CountAccountsByUserID(userID uuid.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountAccountsByUserID", userID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountAccountsByUserID indicates an expected call of CountAccountsByUserID.
func (mr *MockUserRepositoryInterfaceMockRecorder) CountAccountsByUserID(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountAccountsByUserID", reflect.TypeOf((*MockUserRepositoryInterface)(nil).CountAccountsByUserID), userID)
}

// Create mocks base method.
func (m *MockUserRepositoryInterface) Create(user *models.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", user)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockUserRepositoryInterfaceMockRecorder) Create(user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserRepositoryInterface)(nil).Create), user)
}

// Delete mocks base method.
func (m *MockUserRepositoryInterface) Delete(userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockUserRepositoryInterfaceMockRecorder) Delete(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockUserRepositoryInterface)(nil).Delete), userID)
}

// GetByEmail mocks base method.
func (m *MockUserRepositoryInterface) GetByEmail(email string) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEmail", email)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByEmail indicates an expected call of GetByEmail.
func (mr *MockUserRepositoryInterfaceMockRecorder) GetByEmail(email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEmail", reflect.TypeOf((*MockUserRepositoryInterface)(nil).GetByEmail), email)
}

// GetByEmailExcluding mocks base method.
func (m *MockUserRepositoryInterface) GetByEmailExcluding(email string, excludeUserID uuid.UUID) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEmailExcluding", email, excludeUserID)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByEmailExcluding indicates an expected call of GetByEmailExcluding.
func (mr *MockUserRepositoryInterfaceMockRecorder) GetByEmailExcluding(email, excludeUserID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEmailExcluding", reflect.TypeOf((*MockUserRepositoryInterface)(nil).GetByEmailExcluding), email, excludeUserID)
}

// GetByID mocks base method.
func (m *MockUserRepositoryInterface) GetByID(id uuid.UUID) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", id)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockUserRepositoryInterfaceMockRecorder) GetByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockUserRepositoryInterface)(nil).GetByID), id)
}

// GetByIDActive mocks base method.
func (m *MockUserRepositoryInterface) GetByIDActive(id uuid.UUID) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIDActive", id)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIDActive indicates an expected call of GetByIDActive.
func (mr *MockUserRepositoryInterfaceMockRecorder) GetByIDActive(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIDActive", reflect.TypeOf((*MockUserRepositoryInterface)(nil).GetByIDActive), id)
}

// ListUsers mocks base method.
func (m *MockUserRepositoryInterface) ListUsers(offset, limit int) ([]*models.User, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUsers", offset, limit)
	ret0, _ := ret[0].([]*models.User)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListUsers indicates an expected call of ListUsers.
func (mr *MockUserRepositoryInterfaceMockRecorder) ListUsers(offset, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUsers", reflect.TypeOf((*MockUserRepositoryInterface)(nil).ListUsers), offset, limit)
}

// ResetFailedLoginAttempts mocks base method.
func (m *MockUserRepositoryInterface) ResetFailedLoginAttempts(userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetFailedLoginAttempts", userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResetFailedLoginAttempts indicates an expected call of ResetFailedLoginAttempts.
func (mr *MockUserRepositoryInterfaceMockRecorder) ResetFailedLoginAttempts(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetFailedLoginAttempts", reflect.TypeOf((*MockUserRepositoryInterface)(nil).ResetFailedLoginAttempts), userID)
}

// SearchUsers mocks base method.
func (m *MockUserRepositoryInterface) SearchUsers(criteria repositories.UserSearchCriteria, offset, limit int) ([]*models.User, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchUsers", criteria, offset, limit)
	ret0, _ := ret[0].([]*models.User)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SearchUsers indicates an expected call of SearchUsers.
func (mr *MockUserRepositoryInterfaceMockRecorder) SearchUsers(criteria, offset, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchUsers", reflect.TypeOf((*MockUserRepositoryInterface)(nil).SearchUsers), criteria, offset, limit)
}

// UnlockAccount mocks base method.
func (m *MockUserRepositoryInterface) UnlockAccount(userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnlockAccount", userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnlockAccount indicates an expected call of UnlockAccount.
func (mr *MockUserRepositoryInterfaceMockRecorder) UnlockAccount(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnlockAccount", reflect.TypeOf((*MockUserRepositoryInterface)(nil).UnlockAccount), userID)
}

// Update mocks base method.
func (m *MockUserRepositoryInterface) Update(user *models.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", user)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockUserRepositoryInterfaceMockRecorder) Update(user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUserRepositoryInterface)(nil).Update), user)
}

// UpdateEmail mocks base method.
func (m *MockUserRepositoryInterface) UpdateEmail(userID uuid.UUID, newEmail string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateEmail", userID, newEmail)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateEmail indicates an expected call of UpdateEmail.
func (mr *MockUserRepositoryInterfaceMockRecorder) UpdateEmail(userID, newEmail interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEmail", reflect.TypeOf((*MockUserRepositoryInterface)(nil).UpdateEmail), userID, newEmail)
}

// UpdateFailedLoginAttempts mocks base method.
func (m *MockUserRepositoryInterface) UpdateFailedLoginAttempts(user *models.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateFailedLoginAttempts", user)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateFailedLoginAttempts indicates an expected call of UpdateFailedLoginAttempts.
func (mr *MockUserRepositoryInterfaceMockRecorder) UpdateFailedLoginAttempts(user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateFailedLoginAttempts", reflect.TypeOf((*MockUserRepositoryInterface)(nil).UpdateFailedLoginAttempts), user)
}

// UpdateFields mocks base method.
func (m *MockUserRepositoryInterface) UpdateFields(userID uuid.UUID, fields map[string]interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateFields", userID, fields)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateFields indicates an expected call of UpdateFields.
func (mr *MockUserRepositoryInterfaceMockRecorder) UpdateFields(userID, fields interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateFields", reflect.TypeOf((*MockUserRepositoryInterface)(nil).UpdateFields), userID, fields)
}

// UpdatePasswordHash mocks base method.
func (m *MockUserRepositoryInterface) UpdatePasswordHash(userID uuid.UUID, passwordHash string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePasswordHash", userID, passwordHash)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePasswordHash indicates an expected call of UpdatePasswordHash.
func (mr *MockUserRepositoryInterfaceMockRecorder) UpdatePasswordHash(userID, passwordHash interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePasswordHash", reflect.TypeOf((*MockUserRepositoryInterface)(nil).UpdatePasswordHash), userID, passwordHash)
}

// MockAuditLogRepositoryInterface is a mock of AuditLogRepositoryInterface interface.
type MockAuditLogRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockAuditLogRepositoryInterfaceMockRecorder
}

// MockAuditLogRepositoryInterfaceMockRecorder is the mock recorder for MockAuditLogRepositoryInterface.
type MockAuditLogRepositoryInterfaceMockRecorder struct {
	mock *MockAuditLogRepositoryInterface
}

// NewMockAuditLogRepositoryInterface creates a new mock instance.
func NewMockAuditLogRepositoryInterface(ctrl *gomock.Controller) *MockAuditLogRepositoryInterface {
	mock := &MockAuditLogRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockAuditLogRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuditLogRepositoryInterface) EXPECT() *MockAuditLogRepositoryInterfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockAuditLogRepositoryInterface) Create(log *models.AuditLog) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", log)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockAuditLogRepositoryInterfaceMockRecorder) Create(log interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAuditLogRepositoryInterface)(nil).Create), log)
}

// DeleteOlderThan mocks base method.
func (m *MockAuditLogRepositoryInterface) DeleteOlderThan(duration time.Duration) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOlderThan", duration)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteOlderThan indicates an expected call of DeleteOlderThan.
func (mr *MockAuditLogRepositoryInterfaceMockRecorder) DeleteOlderThan(duration interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOlderThan", reflect.TypeOf((*MockAuditLogRepositoryInterface)(nil).DeleteOlderThan), duration)
}

// GetByAction mocks base method.
func (m *MockAuditLogRepositoryInterface) GetByAction(action string, offset, limit int) ([]*models.AuditLog, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByAction", action, offset, limit)
	ret0, _ := ret[0].([]*models.AuditLog)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetByAction indicates an expected call of GetByAction.
func (mr *MockAuditLogRepositoryInterfaceMockRecorder) GetByAction(action, offset, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByAction", reflect.TypeOf((*MockAuditLogRepositoryInterface)(nil).GetByAction), action, offset, limit)
}

// GetByID mocks base method.
func (m *MockAuditLogRepositoryInterface) GetByID(id uuid.UUID) (*models.AuditLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", id)
	ret0, _ := ret[0].(*models.AuditLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockAuditLogRepositoryInterfaceMockRecorder) GetByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockAuditLogRepositoryInterface)(nil).GetByID), id)
}

// GetByIPAddress mocks base method.
func (m *MockAuditLogRepositoryInterface) GetByIPAddress(ipAddress string, offset, limit int) ([]*models.AuditLog, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIPAddress", ipAddress, offset, limit)
	ret0, _ := ret[0].([]*models.AuditLog)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetByIPAddress indicates an expected call of GetByIPAddress.
func (mr *MockAuditLogRepositoryInterfaceMockRecorder) GetByIPAddress(ipAddress, offset, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIPAddress", reflect.TypeOf((*MockAuditLogRepositoryInterface)(nil).GetByIPAddress), ipAddress, offset, limit)
}

// GetByResource mocks base method.
func (m *MockAuditLogRepositoryInterface) GetByResource(resource, resourceID string, offset, limit int) ([]*models.AuditLog, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByResource", resource, resourceID, offset, limit)
	ret0, _ := ret[0].([]*models.AuditLog)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetByResource indicates an expected call of GetByResource.
func (mr *MockAuditLogRepositoryInterfaceMockRecorder) GetByResource(resource, resourceID, offset, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByResource", reflect.TypeOf((*MockAuditLogRepositoryInterface)(nil).GetByResource), resource, resourceID, offset, limit)
}

// GetByTimeRange mocks base method.
func (m *MockAuditLogRepositoryInterface) GetByTimeRange(startTime, endTime time.Time, offset, limit int) ([]*models.AuditLog, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByTimeRange", startTime, endTime, offset, limit)
	ret0, _ := ret[0].([]*models.AuditLog)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetByTimeRange indicates an expected call of GetByTimeRange.
func (mr *MockAuditLogRepositoryInterfaceMockRecorder) GetByTimeRange(startTime, endTime, offset, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByTimeRange", reflect.TypeOf((*MockAuditLogRepositoryInterface)(nil).GetByTimeRange), startTime, endTime, offset, limit)
}

// GetByUserID mocks base method.
func (m *MockAuditLogRepositoryInterface) GetByUserID(userID uuid.UUID, offset, limit int) ([]*models.AuditLog, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserID", userID, offset, limit)
	ret0, _ := ret[0].([]*models.AuditLog)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetByUserID indicates an expected call of GetByUserID.
func (mr *MockAuditLogRepositoryInterfaceMockRecorder) GetByUserID(userID, offset, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserID", reflect.TypeOf((*MockAuditLogRepositoryInterface)(nil).GetByUserID), userID, offset, limit)
}

// GetCustomerActivity mocks base method.
func (m *MockAuditLogRepositoryInterface) GetCustomerActivity(userID uuid.UUID, startDate, endDate *time.Time, offset, limit int) ([]*models.AuditLog, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCustomerActivity", userID, startDate, endDate, offset, limit)
	ret0, _ := ret[0].([]*models.AuditLog)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetCustomerActivity indicates an expected call of GetCustomerActivity.
func (mr *MockAuditLogRepositoryInterfaceMockRecorder) GetCustomerActivity(userID, startDate, endDate, offset, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCustomerActivity", reflect.TypeOf((*MockAuditLogRepositoryInterface)(nil).GetCustomerActivity), userID, startDate, endDate, offset, limit)
}

// GetFailedLoginAttempts mocks base method.
func (m *MockAuditLogRepositoryInterface) GetFailedLoginAttempts(email string, since time.Time) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFailedLoginAttempts", email, since)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFailedLoginAttempts indicates an expected call of GetFailedLoginAttempts.
func (mr *MockAuditLogRepositoryInterfaceMockRecorder) GetFailedLoginAttempts(email, since interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFailedLoginAttempts", reflect.TypeOf((*MockAuditLogRepositoryInterface)(nil).GetFailedLoginAttempts), email, since)
}

// MockProcessingQueueRepositoryInterface is a mock of ProcessingQueueRepositoryInterface interface.
type MockProcessingQueueRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockProcessingQueueRepositoryInterfaceMockRecorder
}

// MockProcessingQueueRepositoryInterfaceMockRecorder is the mock recorder for MockProcessingQueueRepositoryInterface.
type MockProcessingQueueRepositoryInterfaceMockRecorder struct {
	mock *MockProcessingQueueRepositoryInterface
}

// NewMockProcessingQueueRepositoryInterface creates a new mock instance.
func NewMockProcessingQueueRepositoryInterface(ctrl *gomock.Controller) *MockProcessingQueueRepositoryInterface {
	mock := &MockProcessingQueueRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockProcessingQueueRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProcessingQueueRepositoryInterface) EXPECT() *MockProcessingQueueRepositoryInterfaceMockRecorder {
	return m.recorder
}

// CleanupCompleted mocks base method.
func (m *MockProcessingQueueRepositoryInterface) CleanupCompleted(olderThan time.Duration) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CleanupCompleted", olderThan)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CleanupCompleted indicates an expected call of CleanupCompleted.
func (mr *MockProcessingQueueRepositoryInterfaceMockRecorder) CleanupCompleted(olderThan interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CleanupCompleted", reflect.TypeOf((*MockProcessingQueueRepositoryInterface)(nil).CleanupCompleted), olderThan)
}

// Enqueue mocks base method.
func (m *MockProcessingQueueRepositoryInterface) Enqueue(transactionID uuid.UUID, operation string, priority int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Enqueue", transactionID, operation, priority)
	ret0, _ := ret[0].(error)
	return ret0
}

// Enqueue indicates an expected call of Enqueue.
func (mr *MockProcessingQueueRepositoryInterfaceMockRecorder) Enqueue(transactionID, operation, priority interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enqueue", reflect.TypeOf((*MockProcessingQueueRepositoryInterface)(nil).Enqueue), transactionID, operation, priority)
}

// FetchPending mocks base method.
func (m *MockProcessingQueueRepositoryInterface) FetchPending(limit int) ([]*models.ProcessingQueueItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchPending", limit)
	ret0, _ := ret[0].([]*models.ProcessingQueueItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchPending indicates an expected call of FetchPending.
func (mr *MockProcessingQueueRepositoryInterfaceMockRecorder) FetchPending(limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchPending", reflect.TypeOf((*MockProcessingQueueRepositoryInterface)(nil).FetchPending), limit)
}

// GetAverageProcessingTime mocks base method.
func (m *MockProcessingQueueRepositoryInterface) GetAverageProcessingTime() (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAverageProcessingTime")
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAverageProcessingTime indicates an expected call of GetAverageProcessingTime.
func (mr *MockProcessingQueueRepositoryInterfaceMockRecorder) GetAverageProcessingTime() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAverageProcessingTime", reflect.TypeOf((*MockProcessingQueueRepositoryInterface)(nil).GetAverageProcessingTime))
}

// GetCompletedCount mocks base method.
func (m *MockProcessingQueueRepositoryInterface) GetCompletedCount() (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCompletedCount")
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCompletedCount indicates an expected call of GetCompletedCount.
func (mr *MockProcessingQueueRepositoryInterfaceMockRecorder) GetCompletedCount() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCompletedCount", reflect.TypeOf((*MockProcessingQueueRepositoryInterface)(nil).GetCompletedCount))
}

// GetFailedCount mocks base method.
func (m *MockProcessingQueueRepositoryInterface) GetFailedCount() (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFailedCount")
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFailedCount indicates an expected call of GetFailedCount.
func (mr *MockProcessingQueueRepositoryInterfaceMockRecorder) GetFailedCount() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFailedCount", reflect.TypeOf((*MockProcessingQueueRepositoryInterface)(nil).GetFailedCount))
}

// GetOldestPendingAge mocks base method.
func (m *MockProcessingQueueRepositoryInterface) GetOldestPendingAge() (*string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOldestPendingAge")
	ret0, _ := ret[0].(*string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOldestPendingAge indicates an expected call of GetOldestPendingAge.
func (mr *MockProcessingQueueRepositoryInterfaceMockRecorder) GetOldestPendingAge() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOldestPendingAge", reflect.TypeOf((*MockProcessingQueueRepositoryInterface)(nil).GetOldestPendingAge))
}

// GetPendingCount mocks base method.
func (m *MockProcessingQueueRepositoryInterface) GetPendingCount() (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPendingCount")
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPendingCount indicates an expected call of GetPendingCount.
func (mr *MockProcessingQueueRepositoryInterfaceMockRecorder) GetPendingCount() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPendingCount", reflect.TypeOf((*MockProcessingQueueRepositoryInterface)(nil).GetPendingCount))
}

// GetProcessingCount mocks base method.
func (m *MockProcessingQueueRepositoryInterface) GetProcessingCount() (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProcessingCount")
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProcessingCount indicates an expected call of GetProcessingCount.
func (mr *MockProcessingQueueRepositoryInterfaceMockRecorder) GetProcessingCount() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProcessingCount", reflect.TypeOf((*MockProcessingQueueRepositoryInterface)(nil).GetProcessingCount))
}

// IncrementRetry mocks base method.
func (m *MockProcessingQueueRepositoryInterface) IncrementRetry(queueItemID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementRetry", queueItemID)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrementRetry indicates an expected call of IncrementRetry.
func (mr *MockProcessingQueueRepositoryInterfaceMockRecorder) IncrementRetry(queueItemID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementRetry", reflect.TypeOf((*MockProcessingQueueRepositoryInterface)(nil).IncrementRetry), queueItemID)
}

// MarkCompleted mocks base method.
func (m *MockProcessingQueueRepositoryInterface) MarkCompleted(queueItemID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkCompleted", queueItemID)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkCompleted indicates an expected call of MarkCompleted.
func (mr *MockProcessingQueueRepositoryInterfaceMockRecorder) MarkCompleted(queueItemID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkCompleted", reflect.TypeOf((*MockProcessingQueueRepositoryInterface)(nil).MarkCompleted), queueItemID)
}

// MarkFailed mocks base method.
func (m *MockProcessingQueueRepositoryInterface) MarkFailed(queueItemID uuid.UUID, errorMessage string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkFailed", queueItemID, errorMessage)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkFailed indicates an expected call of MarkFailed.
func (mr *MockProcessingQueueRepositoryInterfaceMockRecorder) MarkFailed(queueItemID, errorMessage interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkFailed", reflect.TypeOf((*MockProcessingQueueRepositoryInterface)(nil).MarkFailed), queueItemID, errorMessage)
}

// MarkProcessing mocks base method.
func (m *MockProcessingQueueRepositoryInterface) MarkProcessing(queueItemID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkProcessing", queueItemID)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkProcessing indicates an expected call of MarkProcessing.
func (mr *MockProcessingQueueRepositoryInterfaceMockRecorder) MarkProcessing(queueItemID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkProcessing", reflect.TypeOf((*MockProcessingQueueRepositoryInterface)(nil).MarkProcessing), queueItemID)
}

// MockTransferRepositoryInterface is a mock of TransferRepositoryInterface interface.
type MockTransferRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockTransferRepositoryInterfaceMockRecorder
}

// MockTransferRepositoryInterfaceMockRecorder is the mock recorder for MockTransferRepositoryInterface.
type MockTransferRepositoryInterfaceMockRecorder struct {
	mock *MockTransferRepositoryInterface
}

// NewMockTransferRepositoryInterface creates a new mock instance.
func NewMockTransferRepositoryInterface(ctrl *gomock.Controller) *MockTransferRepositoryInterface {
	mock := &MockTransferRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockTransferRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransferRepositoryInterface) EXPECT() *MockTransferRepositoryInterfaceMockRecorder {
	return m.recorder
}

// CountByUserAccounts mocks base method.
func (m *MockTransferRepositoryInterface) CountByUserAccounts(accountIDs []uuid.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByUserAccounts", accountIDs)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByUserAccounts indicates an expected call of CountByUserAccounts.
func (mr *MockTransferRepositoryInterfaceMockRecorder) CountByUserAccounts(accountIDs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByUserAccounts", reflect.TypeOf((*MockTransferRepositoryInterface)(nil).CountByUserAccounts), accountIDs)
}

// Create mocks base method.
func (m *MockTransferRepositoryInterface) Create(transfer *models.Transfer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", transfer)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockTransferRepositoryInterfaceMockRecorder) Create(transfer interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTransferRepositoryInterface)(nil).Create), transfer)
}

// FindByID mocks base method.
func (m *MockTransferRepositoryInterface) FindByID(id uuid.UUID) (*models.Transfer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", id)
	ret0, _ := ret[0].(*models.Transfer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockTransferRepositoryInterfaceMockRecorder) FindByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockTransferRepositoryInterface)(nil).FindByID), id)
}

// FindByIdempotencyKey mocks base method.
func (m *MockTransferRepositoryInterface) FindByIdempotencyKey(key string) (*models.Transfer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByIdempotencyKey", key)
	ret0, _ := ret[0].(*models.Transfer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByIdempotencyKey indicates an expected call of FindByIdempotencyKey.
func (mr *MockTransferRepositoryInterfaceMockRecorder) FindByIdempotencyKey(key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByIdempotencyKey", reflect.TypeOf((*MockTransferRepositoryInterface)(nil).FindByIdempotencyKey), key)
}

// FindByUserAccounts mocks base method.
func (m *MockTransferRepositoryInterface) FindByUserAccounts(accountIDs []uuid.UUID, offset, limit int) ([]models.Transfer, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUserAccounts", accountIDs, offset, limit)
	ret0, _ := ret[0].([]models.Transfer)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindByUserAccounts indicates an expected call of FindByUserAccounts.
func (mr *MockTransferRepositoryInterfaceMockRecorder) FindByUserAccounts(accountIDs, offset, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUserAccounts", reflect.TypeOf((*MockTransferRepositoryInterface)(nil).FindByUserAccounts), accountIDs, offset, limit)
}

// FindByUserAccountsWithFilters mocks base method.
func (m *MockTransferRepositoryInterface) FindByUserAccountsWithFilters(accountIDs []uuid.UUID, filters models.TransferFilters, offset, limit int) ([]models.Transfer, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUserAccountsWithFilters", accountIDs, filters, offset, limit)
	ret0, _ := ret[0].([]models.Transfer)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindByUserAccountsWithFilters indicates an expected call of FindByUserAccountsWithFilters.
func (mr *MockTransferRepositoryInterfaceMockRecorder) FindByUserAccountsWithFilters(accountIDs, filters, offset, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUserAccountsWithFilters", reflect.TypeOf((*MockTransferRepositoryInterface)(nil).FindByUserAccountsWithFilters), accountIDs, filters, offset, limit)
}

// Update mocks base method.
func (m *MockTransferRepositoryInterface) Update(transfer *models.Transfer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", transfer)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockTransferRepositoryInterfaceMockRecorder) Update(transfer interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockTransferRepositoryInterface)(nil).Update), transfer)
}

// MockRefreshTokenRepositoryInterface is a mock of RefreshTokenRepositoryInterface interface.
type MockRefreshTokenRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockRefreshTokenRepositoryInterfaceMockRecorder
}

// MockRefreshTokenRepositoryInterfaceMockRecorder is the mock recorder for MockRefreshTokenRepositoryInterface.
type MockRefreshTokenRepositoryInterfaceMockRecorder struct {
	mock *MockRefreshTokenRepositoryInterface
}

// NewMockRefreshTokenRepositoryInterface creates a new mock instance.
func NewMockRefreshTokenRepositoryInterface(ctrl *gomock.Controller) *MockRefreshTokenRepositoryInterface {
	mock := &MockRefreshTokenRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockRefreshTokenRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRefreshTokenRepositoryInterface) EXPECT() *MockRefreshTokenRepositoryInterfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRefreshTokenRepositoryInterface) Create(token *models.RefreshToken) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", token)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRefreshTokenRepositoryInterfaceMockRecorder) Create(token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRefreshTokenRepositoryInterface)(nil).Create), token)
}

// DeleteExpired mocks base method.
func (m *MockRefreshTokenRepositoryInterface) DeleteExpired() (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteExpired")
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteExpired indicates an expected call of DeleteExpired.
func (mr *MockRefreshTokenRepositoryInterfaceMockRecorder) DeleteExpired() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteExpired", reflect.TypeOf((*MockRefreshTokenRepositoryInterface)(nil).DeleteExpired))
}

// DeleteRevokedOlderThan mocks base method.
func (m *MockRefreshTokenRepositoryInterface) DeleteRevokedOlderThan(duration time.Duration) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRevokedOlderThan", duration)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteRevokedOlderThan indicates an expected call of DeleteRevokedOlderThan.
func (mr *MockRefreshTokenRepositoryInterfaceMockRecorder) DeleteRevokedOlderThan(duration interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRevokedOlderThan", reflect.TypeOf((*MockRefreshTokenRepositoryInterface)(nil).DeleteRevokedOlderThan), duration)
}

// GetActiveByUserID mocks base method.
func (m *MockRefreshTokenRepositoryInterface) GetActiveByUserID(userID uuid.UUID) ([]*models.RefreshToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveByUserID", userID)
	ret0, _ := ret[0].([]*models.RefreshToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveByUserID indicates an expected call of GetActiveByUserID.
func (mr *MockRefreshTokenRepositoryInterfaceMockRecorder) GetActiveByUserID(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveByUserID", reflect.TypeOf((*MockRefreshTokenRepositoryInterface)(nil).GetActiveByUserID), userID)
}

// GetByID mocks base method.
func (m *MockRefreshTokenRepositoryInterface) GetByID(id uuid.UUID) (*models.RefreshToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", id)
	ret0, _ := ret[0].(*models.RefreshToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockRefreshTokenRepositoryInterfaceMockRecorder) GetByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockRefreshTokenRepositoryInterface)(nil).GetByID), id)
}

// GetByTokenHash mocks base method.
func (m *MockRefreshTokenRepositoryInterface) GetByTokenHash(tokenHash string) (*models.RefreshToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByTokenHash", tokenHash)
	ret0, _ := ret[0].(*models.RefreshToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByTokenHash indicates an expected call of GetByTokenHash.
func (mr *MockRefreshTokenRepositoryInterfaceMockRecorder) GetByTokenHash(tokenHash interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByTokenHash", reflect.TypeOf((*MockRefreshTokenRepositoryInterface)(nil).GetByTokenHash), tokenHash)
}

// Revoke mocks base method.
func (m *MockRefreshTokenRepositoryInterface) Revoke(tokenID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Revoke", tokenID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Revoke indicates an expected call of Revoke.
func (mr *MockRefreshTokenRepositoryInterfaceMockRecorder) Revoke(tokenID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Revoke", reflect.TypeOf((*MockRefreshTokenRepositoryInterface)(nil).Revoke), tokenID)
}

// RevokeAllForUser mocks base method.
func (m *MockRefreshTokenRepositoryInterface) RevokeAllForUser(userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeAllForUser", userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeAllForUser indicates an expected call of RevokeAllForUser.
func (mr *MockRefreshTokenRepositoryInterfaceMockRecorder) RevokeAllForUser(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeAllForUser", reflect.TypeOf((*MockRefreshTokenRepositoryInterface)(nil).RevokeAllForUser), userID)
}

// Update mocks base method.
func (m *MockRefreshTokenRepositoryInterface) Update(token *models.RefreshToken) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", token)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockRefreshTokenRepositoryInterfaceMockRecorder) Update(token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRefreshTokenRepositoryInterface)(nil).Update), token)
}

// MockBlacklistedTokenRepositoryInterface is a mock of BlacklistedTokenRepositoryInterface interface.
type MockBlacklistedTokenRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockBlacklistedTokenRepositoryInterfaceMockRecorder
}

// MockBlacklistedTokenRepositoryInterfaceMockRecorder is the mock recorder for MockBlacklistedTokenRepositoryInterface.
type MockBlacklistedTokenRepositoryInterfaceMockRecorder struct {
	mock *MockBlacklistedTokenRepositoryInterface
}

// NewMockBlacklistedTokenRepositoryInterface creates a new mock instance.
func NewMockBlacklistedTokenRepositoryInterface(ctrl *gomock.Controller) *MockBlacklistedTokenRepositoryInterface {
	mock := &MockBlacklistedTokenRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockBlacklistedTokenRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBlacklistedTokenRepositoryInterface) EXPECT() *MockBlacklistedTokenRepositoryInterfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockBlacklistedTokenRepositoryInterface) Create(token *models.BlacklistedToken) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", token)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockBlacklistedTokenRepositoryInterfaceMockRecorder) Create(token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockBlacklistedTokenRepositoryInterface)(nil).Create), token)
}

// DeleteExpired mocks base method.
func (m *MockBlacklistedTokenRepositoryInterface) DeleteExpired() (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteExpired")
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteExpired indicates an expected call of DeleteExpired.
func (mr *MockBlacklistedTokenRepositoryInterfaceMockRecorder) DeleteExpired() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteExpired", reflect.TypeOf((*MockBlacklistedTokenRepositoryInterface)(nil).DeleteExpired))
}

// GetByJTI mocks base method.
func (m *MockBlacklistedTokenRepositoryInterface) GetByJTI(jti string) (*models.BlacklistedToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByJTI", jti)
	ret0, _ := ret[0].(*models.BlacklistedToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByJTI indicates an expected call of GetByJTI.
func (mr *MockBlacklistedTokenRepositoryInterfaceMockRecorder) GetByJTI(jti interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByJTI", reflect.TypeOf((*MockBlacklistedTokenRepositoryInterface)(nil).GetByJTI), jti)
}
