// Code generated by MockGen. DO NOT EDIT.
// Source: ../interfaces.go

// Package service_mocks is a generated GoMock package.
package service_mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	dto "array-assessment/internal/dto"
	models "array-assessment/internal/models"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
	decimal "github.com/shopspring/decimal"
)

// MockAccountAssociationServiceInterface is a mock of AccountAssociationServiceInterface interface.
type MockAccountAssociationServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockAccountAssociationServiceInterfaceMockRecorder
}

// MockAccountAssociationServiceInterfaceMockRecorder is the mock recorder for MockAccountAssociationServiceInterface.
type MockAccountAssociationServiceInterfaceMockRecorder struct {
	mock *MockAccountAssociationServiceInterface
}

// NewMockAccountAssociationServiceInterface creates a new mock instance.
func NewMockAccountAssociationServiceInterface(ctrl *gomock.Controller) *MockAccountAssociationServiceInterface {
	mock := &MockAccountAssociationServiceInterface{ctrl: ctrl}
	mock.recorder = &MockAccountAssociationServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccountAssociationServiceInterface) EXPECT() *MockAccountAssociationServiceInterfaceMockRecorder {
	return m.recorder
}

// CreateAccountForCustomer mocks base method.
func (m *MockAccountAssociationServiceInterface) CreateAccountForCustomer(customerID, performedBy uuid.UUID, accountType, ipAddress, userAgent string) (*models.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAccountForCustomer", customerID, performedBy, accountType, ipAddress, userAgent)
	ret0, _ := ret[0].(*models.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAccountForCustomer indicates an expected call of CreateAccountForCustomer.
func (mr *MockAccountAssociationServiceInterfaceMockRecorder) CreateAccountForCustomer(customerID, performedBy, accountType, ipAddress, userAgent interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAccountForCustomer", reflect.TypeOf((*MockAccountAssociationServiceInterface)(nil).CreateAccountForCustomer), customerID, performedBy, accountType, ipAddress, userAgent)
}

// GetCustomerAccounts mocks base method.
func (m *MockAccountAssociationServiceInterface) GetCustomerAccounts(customerID uuid.UUID) ([]*models.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCustomerAccounts", customerID)
	ret0, _ := ret[0].([]*models.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCustomerAccounts indicates an expected call of GetCustomerAccounts.
func (mr *MockAccountAssociationServiceInterfaceMockRecorder) GetCustomerAccounts(customerID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCustomerAccounts", reflect.TypeOf((*MockAccountAssociationServiceInterface)(nil).GetCustomerAccounts), customerID)
}

// TransferAccountOwnership mocks base method.
func (m *MockAccountAssociationServiceInterface) TransferAccountOwnership(accountID, fromCustomerID, toCustomerID, performedBy uuid.UUID, ipAddress, userAgent string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TransferAccountOwnership", accountID, fromCustomerID, toCustomerID, performedBy, ipAddress, userAgent)
	ret0, _ := ret[0].(error)
	return ret0
}

// TransferAccountOwnership indicates an expected call of TransferAccountOwnership.
func (mr *MockAccountAssociationServiceInterfaceMockRecorder) TransferAccountOwnership(accountID, fromCustomerID, toCustomerID, performedBy, ipAddress, userAgent interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TransferAccountOwnership", reflect.TypeOf((*MockAccountAssociationServiceInterface)(nil).TransferAccountOwnership), accountID, fromCustomerID, toCustomerID, performedBy, ipAddress, userAgent)
}

// MockAccountServiceInterface is a mock of AccountServiceInterface interface.
type MockAccountServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockAccountServiceInterfaceMockRecorder
}

// MockAccountServiceInterfaceMockRecorder is the mock recorder for MockAccountServiceInterface.
type MockAccountServiceInterfaceMockRecorder struct {
	mock *MockAccountServiceInterface
}

// NewMockAccountServiceInterface creates a new mock instance.
func NewMockAccountServiceInterface(ctrl *gomock.Controller) *MockAccountServiceInterface {
	mock := &MockAccountServiceInterface{ctrl: ctrl}
	mock.recorder = &MockAccountServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccountServiceInterface) EXPECT() *MockAccountServiceInterfaceMockRecorder {
	return m.recorder
}

// CloseAccount mocks base method.
func (m *MockAccountServiceInterface) CloseAccount(accountID, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseAccount", accountID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseAccount indicates an expected call of CloseAccount.
func (mr *MockAccountServiceInterfaceMockRecorder) CloseAccount(accountID, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseAccount", reflect.TypeOf((*MockAccountServiceInterface)(nil).CloseAccount), accountID, userID)
}

// CreateAccount mocks base method.
func (m *MockAccountServiceInterface) CreateAccount(userID uuid.UUID, accountType string, initialDeposit decimal.Decimal) (*models.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAccount", userID, accountType, initialDeposit)
	ret0, _ := ret[0].(*models.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAccount indicates an expected call of CreateAccount.
func (mr *MockAccountServiceInterfaceMockRecorder) CreateAccount(userID, accountType, initialDeposit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAccount", reflect.TypeOf((*MockAccountServiceInterface)(nil).CreateAccount), userID, accountType, initialDeposit)
}

// CreateAccountsForNewUser mocks base method.
func (m *MockAccountServiceInterface) CreateAccountsForNewUser(userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAccountsForNewUser", userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateAccountsForNewUser indicates an expected call of CreateAccountsForNewUser.
func (mr *MockAccountServiceInterfaceMockRecorder) CreateAccountsForNewUser(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAccountsForNewUser", reflect.TypeOf((*MockAccountServiceInterface)(nil).CreateAccountsForNewUser), userID)
}

// GetAccountByID mocks base method.
func (m *MockAccountServiceInterface) GetAccountByID(accountID uuid.UUID, userID *uuid.UUID) (*models.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountByID", accountID, userID)
	ret0, _ := ret[0].(*models.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountByID indicates an expected call of GetAccountByID.
func (mr *MockAccountServiceInterfaceMockRecorder) GetAccountByID(accountID, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountByID", reflect.TypeOf((*MockAccountServiceInterface)(nil).GetAccountByID), accountID, userID)
}

// GetAccountByNumber mocks base method.
func (m *MockAccountServiceInterface) GetAccountByNumber(accountNumber string) (*models.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountByNumber", accountNumber)
	ret0, _ := ret[0].(*models.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountByNumber indicates an expected call of GetAccountByNumber.
func (mr *MockAccountServiceInterfaceMockRecorder) GetAccountByNumber(accountNumber interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountByNumber", reflect.TypeOf((*MockAccountServiceInterface)(nil).GetAccountByNumber), accountNumber)
}

// GetAccountTransactions mocks base method.
func (m *MockAccountServiceInterface) GetAccountTransactions(accountID uuid.UUID, userID *uuid.UUID, offset, limit int) ([]models.Transaction, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountTransactions", accountID, userID, offset, limit)
	ret0, _ := ret[0].([]models.Transaction)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetAccountTransactions indicates an expected call of GetAccountTransactions.
func (mr *MockAccountServiceInterfaceMockRecorder) GetAccountTransactions(accountID, userID, offset, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountTransactions", reflect.TypeOf((*MockAccountServiceInterface)(nil).GetAccountTransactions), accountID, userID, offset, limit)
}

// GetAllAccounts mocks base method.
func (m *MockAccountServiceInterface) GetAllAccounts(filters models.AccountFilters, offset, limit int) ([]models.Account, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllAccounts", filters, offset, limit)
	ret0, _ := ret[0].([]models.Account)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetAllAccounts indicates an expected call of GetAllAccounts.
func (mr *MockAccountServiceInterfaceMockRecorder) GetAllAccounts(filters, offset, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllAccounts", reflect.TypeOf((*MockAccountServiceInterface)(nil).GetAllAccounts), filters, offset, limit)
}

// GetRecentTransactions mocks base method.
func (m *MockAccountServiceInterface) GetRecentTransactions(accountID uuid.UUID, userID *uuid.UUID, limit int) ([]models.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRecentTransactions", accountID, userID, limit)
	ret0, _ := ret[0].([]models.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRecentTransactions indicates an expected call of GetRecentTransactions.
func (mr *MockAccountServiceInterfaceMockRecorder) GetRecentTransactions(accountID, userID, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRecentTransactions", reflect.TypeOf((*MockAccountServiceInterface)(nil).GetRecentTransactions), accountID, userID, limit)
}

// GetUserAccounts mocks base method.
func (m *MockAccountServiceInterface) GetUserAccounts(userID uuid.UUID) ([]models.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserAccounts", userID)
	ret0, _ := ret[0].([]models.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserAccounts indicates an expected call of GetUserAccounts.
func (mr *MockAccountServiceInterfaceMockRecorder) GetUserAccounts(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserAccounts", reflect.TypeOf((*MockAccountServiceInterface)(nil).GetUserAccounts), userID)
}

// GetUserTransfers mocks base method.
func (m *MockAccountServiceInterface) GetUserTransfers(userID uuid.UUID, filters models.TransferFilters, offset, limit int) ([]models.Transfer, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserTransfers", userID, filters, offset, limit)
	ret0, _ := ret[0].([]models.Transfer)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetUserTransfers indicates an expected call of GetUserTransfers.
func (mr *MockAccountServiceInterfaceMockRecorder) GetUserTransfers(userID, filters, offset, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserTransfers", reflect.TypeOf((*MockAccountServiceInterface)(nil).GetUserTransfers), userID, filters, offset, limit)
}

// PerformTransaction mocks base method.
func (m *MockAccountServiceInterface) PerformTransaction(accountID uuid.UUID, amount decimal.Decimal, transactionType, description string, userID *uuid.UUID) (*models.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PerformTransaction", accountID, amount, transactionType, description, userID)
	ret0, _ := ret[0].(*models.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PerformTransaction indicates an expected call of PerformTransaction.
func (mr *MockAccountServiceInterfaceMockRecorder) PerformTransaction(accountID, amount, transactionType, description, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PerformTransaction", reflect.TypeOf((*MockAccountServiceInterface)(nil).PerformTransaction), accountID, amount, transactionType, description, userID)
}

// TransferBetweenAccounts mocks base method.
func (m *MockAccountServiceInterface) TransferBetweenAccounts(fromAccountID, toAccountID uuid.UUID, amount decimal.Decimal, description, idempotencyKey string, userID uuid.UUID) (*models.Transfer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TransferBetweenAccounts", fromAccountID, toAccountID, amount, description, idempotencyKey, userID)
	ret0, _ := ret[0].(*models.Transfer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TransferBetweenAccounts indicates an expected call of TransferBetweenAccounts.
func (mr *MockAccountServiceInterfaceMockRecorder) TransferBetweenAccounts(fromAccountID, toAccountID, amount, description, idempotencyKey, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TransferBetweenAccounts", reflect.TypeOf((*MockAccountServiceInterface)(nil).TransferBetweenAccounts), fromAccountID, toAccountID, amount, description, idempotencyKey, userID)
}

// UpdateAccountStatus mocks base method.
func (m *MockAccountServiceInterface) UpdateAccountStatus(accountID uuid.UUID, userID *uuid.UUID, status string) (*models.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAccountStatus", accountID, userID, status)
	ret0, _ := ret[0].(*models.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateAccountStatus indicates an expected call of UpdateAccountStatus.
func (mr *MockAccountServiceInterfaceMockRecorder) UpdateAccountStatus(accountID, userID, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAccountStatus", reflect.TypeOf((*MockAccountServiceInterface)(nil).UpdateAccountStatus), accountID, userID, status)
}

// MockAccountSummaryServiceInterface is a mock of AccountSummaryServiceInterface interface.
type MockAccountSummaryServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockAccountSummaryServiceInterfaceMockRecorder
}

// MockAccountSummaryServiceInterfaceMockRecorder is the mock recorder for MockAccountSummaryServiceInterface.
type MockAccountSummaryServiceInterfaceMockRecorder struct {
	mock *MockAccountSummaryServiceInterface
}

// NewMockAccountSummaryServiceInterface creates a new mock instance.
func NewMockAccountSummaryServiceInterface(ctrl *gomock.Controller) *MockAccountSummaryServiceInterface {
	mock := &MockAccountSummaryServiceInterface{ctrl: ctrl}
	mock.recorder = &MockAccountSummaryServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccountSummaryServiceInterface) EXPECT() *MockAccountSummaryServiceInterfaceMockRecorder {
	return m.recorder
}

// GetAccountSummary mocks base method.
func (m *MockAccountSummaryServiceInterface) GetAccountSummary(requestorID uuid.UUID, targetUserID *uuid.UUID, isAdmin bool) (*models.UserAccountSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountSummary", requestorID, targetUserID, isAdmin)
	ret0, _ := ret[0].(*models.UserAccountSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountSummary indicates an expected call of GetAccountSummary.
func (mr *MockAccountSummaryServiceInterfaceMockRecorder) GetAccountSummary(requestorID, targetUserID, isAdmin interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountSummary", reflect.TypeOf((*MockAccountSummaryServiceInterface)(nil).GetAccountSummary), requestorID, targetUserID, isAdmin)
}

// MockAuditServiceInterface is a mock of AuditServiceInterface interface.
type MockAuditServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockAuditServiceInterfaceMockRecorder
}

// MockAuditServiceInterfaceMockRecorder is the mock recorder for MockAuditServiceInterface.
type MockAuditServiceInterfaceMockRecorder struct {
	mock *MockAuditServiceInterface
}

// NewMockAuditServiceInterface creates a new mock instance.
func NewMockAuditServiceInterface(ctrl *gomock.Controller) *MockAuditServiceInterface {
	mock := &MockAuditServiceInterface{ctrl: ctrl}
	mock.recorder = &MockAuditServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuditServiceInterface) EXPECT() *MockAuditServiceInterfaceMockRecorder {
	return m.recorder
}

// CreateAuditLog mocks base method.
func (m *MockAuditServiceInterface) CreateAuditLog(log *models.AuditLog) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAuditLog", log)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateAuditLog indicates an expected call of CreateAuditLog.
func (mr *MockAuditServiceInterfaceMockRecorder) CreateAuditLog(log interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAuditLog", reflect.TypeOf((*MockAuditServiceInterface)(nil).CreateAuditLog), log)
}

// GetCustomerActivity mocks base method.
func (m *MockAuditServiceInterface) GetCustomerActivity(userID uuid.UUID, startDate, endDate *time.Time, offset, limit int) ([]*models.AuditLog, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCustomerActivity", userID, startDate, endDate, offset, limit)
	ret0, _ := ret[0].([]*models.AuditLog)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetCustomerActivity indicates an expected call of GetCustomerActivity.
func (mr *MockAuditServiceInterfaceMockRecorder) GetCustomerActivity(userID, startDate, endDate, offset, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCustomerActivity", reflect.TypeOf((*MockAuditServiceInterface)(nil).GetCustomerActivity), userID, startDate, endDate, offset, limit)
}

// LogAccountCreated mocks base method.
func (m *MockAuditServiceInterface) LogAccountCreated(userID, performedBy, accountID uuid.UUID, accountType, ipAddress, userAgent string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LogAccountCreated", userID, performedBy, accountID, accountType, ipAddress, userAgent)
	ret0, _ := ret[0].(error)
	return ret0
}

// LogAccountCreated indicates an expected call of LogAccountCreated.
func (mr *MockAuditServiceInterfaceMockRecorder) LogAccountCreated(userID, performedBy, accountID, accountType, ipAddress, userAgent interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogAccountCreated", reflect.TypeOf((*MockAuditServiceInterface)(nil).LogAccountCreated), userID, performedBy, accountID, accountType, ipAddress, userAgent)
}

// LogAccountTransferred mocks base method.
func (m *MockAuditServiceInterface) LogAccountTransferred(fromUserID, toUserID, performedBy, accountID uuid.UUID, ipAddress, userAgent string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LogAccountTransferred", fromUserID, toUserID, performedBy, accountID, ipAddress, userAgent)
	ret0, _ := ret[0].(error)
	return ret0
}

// LogAccountTransferred indicates an expected call of LogAccountTransferred.
func (mr *MockAuditServiceInterfaceMockRecorder) LogAccountTransferred(fromUserID, toUserID, performedBy, accountID, ipAddress, userAgent interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogAccountTransferred", reflect.TypeOf((*MockAuditServiceInterface)(nil).LogAccountTransferred), fromUserID, toUserID, performedBy, accountID, ipAddress, userAgent)
}

// LogCustomerCreated mocks base method.
func (m *MockAuditServiceInterface) LogCustomerCreated(userID, performedBy uuid.UUID, ipAddress, userAgent string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LogCustomerCreated", userID, performedBy, ipAddress, userAgent)
	ret0, _ := ret[0].(error)
	return ret0
}

// LogCustomerCreated indicates an expected call of LogCustomerCreated.
func (mr *MockAuditServiceInterfaceMockRecorder) LogCustomerCreated(userID, performedBy, ipAddress, userAgent interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogCustomerCreated", reflect.TypeOf((*MockAuditServiceInterface)(nil).LogCustomerCreated), userID, performedBy, ipAddress, userAgent)
}

// LogCustomerDeleted mocks base method.
func (m *MockAuditServiceInterface) LogCustomerDeleted(userID, performedBy uuid.UUID, ipAddress, userAgent, reason string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LogCustomerDeleted", userID, performedBy, ipAddress, userAgent, reason)
	ret0, _ := ret[0].(error)
	return ret0
}

// LogCustomerDeleted indicates an expected call of LogCustomerDeleted.
func (mr *MockAuditServiceInterfaceMockRecorder) LogCustomerDeleted(userID, performedBy, ipAddress, userAgent, reason interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogCustomerDeleted", reflect.TypeOf((*MockAuditServiceInterface)(nil).LogCustomerDeleted), userID, performedBy, ipAddress, userAgent, reason)
}

// LogEmailUpdate mocks base method.
func (m *MockAuditServiceInterface) LogEmailUpdate(userID, performedBy uuid.UUID, oldEmail, newEmail, ipAddress, userAgent string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LogEmailUpdate", userID, performedBy, oldEmail, newEmail, ipAddress, userAgent)
	ret0, _ := ret[0].(error)
	return ret0
}

// LogEmailUpdate indicates an expected call of LogEmailUpdate.
func (mr *MockAuditServiceInterfaceMockRecorder) LogEmailUpdate(userID, performedBy, oldEmail, newEmail, ipAddress, userAgent interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogEmailUpdate", reflect.TypeOf((*MockAuditServiceInterface)(nil).LogEmailUpdate), userID, performedBy, oldEmail, newEmail, ipAddress, userAgent)
}

// LogLogin mocks base method.
func (m *MockAuditServiceInterface) LogLogin(userID uuid.UUID, ipAddress, userAgent string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LogLogin", userID, ipAddress, userAgent)
	ret0, _ := ret[0].(error)
	return ret0
}

// LogLogin indicates an expected call of LogLogin.
func (mr *MockAuditServiceInterfaceMockRecorder) LogLogin(userID, ipAddress, userAgent interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogLogin", reflect.TypeOf((*MockAuditServiceInterface)(nil).LogLogin), userID, ipAddress, userAgent)
}

// LogLogout mocks base method.
func (m *MockAuditServiceInterface) LogLogout(userID uuid.UUID, ipAddress, userAgent string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LogLogout", userID, ipAddress, userAgent)
	ret0, _ := ret[0].(error)
	return ret0
}

// LogLogout indicates an expected call of LogLogout.
func (mr *MockAuditServiceInterfaceMockRecorder) LogLogout(userID, ipAddress, userAgent interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogLogout", reflect.TypeOf((*MockAuditServiceInterface)(nil).LogLogout), userID, ipAddress, userAgent)
}

// LogPasswordReset mocks base method.
func (m *MockAuditServiceInterface) LogPasswordReset(userID, performedBy uuid.UUID, ipAddress, userAgent string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LogPasswordReset", userID, performedBy, ipAddress, userAgent)
	ret0, _ := ret[0].(error)
	return ret0
}

// LogPasswordReset indicates an expected call of LogPasswordReset.
func (mr *MockAuditServiceInterfaceMockRecorder) LogPasswordReset(userID, performedBy, ipAddress, userAgent interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogPasswordReset", reflect.TypeOf((*MockAuditServiceInterface)(nil).LogPasswordReset), userID, performedBy, ipAddress, userAgent)
}

// LogPasswordUpdate mocks base method.
func (m *MockAuditServiceInterface) LogPasswordUpdate(userID uuid.UUID, ipAddress, userAgent string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LogPasswordUpdate", userID, ipAddress, userAgent)
	ret0, _ := ret[0].(error)
	return ret0
}

// LogPasswordUpdate indicates an expected call of LogPasswordUpdate.
func (mr *MockAuditServiceInterfaceMockRecorder) LogPasswordUpdate(userID, ipAddress, userAgent interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogPasswordUpdate", reflect.TypeOf((*MockAuditServiceInterface)(nil).LogPasswordUpdate), userID, ipAddress, userAgent)
}

// LogProfileUpdate mocks base method.
func (m *MockAuditServiceInterface) LogProfileUpdate(userID, performedBy uuid.UUID, ipAddress, userAgent string, changes map[string]interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LogProfileUpdate", userID, performedBy, ipAddress, userAgent, changes)
	ret0, _ := ret[0].(error)
	return ret0
}

// LogProfileUpdate indicates an expected call of LogProfileUpdate.
func (mr *MockAuditServiceInterfaceMockRecorder) LogProfileUpdate(userID, performedBy, ipAddress, userAgent, changes interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogProfileUpdate", reflect.TypeOf((*MockAuditServiceInterface)(nil).LogProfileUpdate), userID, performedBy, ipAddress, userAgent, changes)
}

// MockCategoryServiceInterface is a mock of CategoryServiceInterface interface.
type MockCategoryServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockCategoryServiceInterfaceMockRecorder
}

// MockCategoryServiceInterfaceMockRecorder is the mock recorder for MockCategoryServiceInterface.
type MockCategoryServiceInterfaceMockRecorder struct {
	mock *MockCategoryServiceInterface
}

// NewMockCategoryServiceInterface creates a new mock instance.
func NewMockCategoryServiceInterface(ctrl *gomock.Controller) *MockCategoryServiceInterface {
	mock := &MockCategoryServiceInterface{ctrl: ctrl}
	mock.recorder = &MockCategoryServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCategoryServiceInterface) EXPECT() *MockCategoryServiceInterfaceMockRecorder {
	return m.recorder
}

// BatchCategorize mocks base method.
func (m *MockCategoryServiceInterface) BatchCategorize(transactions []*models.Transaction) []*models.CategorizationResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchCategorize", transactions)
	ret0, _ := ret[0].([]*models.CategorizationResult)
	return ret0
}

// BatchCategorize indicates an expected call of BatchCategorize.
func (mr *MockCategoryServiceInterfaceMockRecorder) BatchCategorize(transactions interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchCategorize", reflect.TypeOf((*MockCategoryServiceInterface)(nil).BatchCategorize), transactions)
}

// CategorizeByDescription mocks base method.
func (m *MockCategoryServiceInterface) CategorizeByDescription(description string) (string, float64) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CategorizeByDescription", description)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(float64)
	return ret0, ret1
}

// CategorizeByDescription indicates an expected call of CategorizeByDescription.
func (mr *MockCategoryServiceInterfaceMockRecorder) CategorizeByDescription(description interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CategorizeByDescription", reflect.TypeOf((*MockCategoryServiceInterface)(nil).CategorizeByDescription), description)
}

// CategorizeByMerchant mocks base method.
func (m *MockCategoryServiceInterface) CategorizeByMerchant(merchantName string) (string, float64) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CategorizeByMerchant", merchantName)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(float64)
	return ret0, ret1
}

// CategorizeByMerchant indicates an expected call of CategorizeByMerchant.
func (mr *MockCategoryServiceInterfaceMockRecorder) CategorizeByMerchant(merchantName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CategorizeByMerchant", reflect.TypeOf((*MockCategoryServiceInterface)(nil).CategorizeByMerchant), merchantName)
}

// CategorizeTransaction mocks base method.
func (m *MockCategoryServiceInterface) CategorizeTransaction(transaction *models.Transaction) *models.CategorizationResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CategorizeTransaction", transaction)
	ret0, _ := ret[0].(*models.CategorizationResult)
	return ret0
}

// CategorizeTransaction indicates an expected call of CategorizeTransaction.
func (mr *MockCategoryServiceInterfaceMockRecorder) CategorizeTransaction(transaction interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CategorizeTransaction", reflect.TypeOf((*MockCategoryServiceInterface)(nil).CategorizeTransaction), transaction)
}

// CategoryFromMCC mocks base method.
func (m *MockCategoryServiceInterface) CategoryFromMCC(mccCode string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CategoryFromMCC", mccCode)
	ret0, _ := ret[0].(string)
	return ret0
}

// CategoryFromMCC indicates an expected call of CategoryFromMCC.
func (mr *MockCategoryServiceInterfaceMockRecorder) CategoryFromMCC(mccCode interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CategoryFromMCC", reflect.TypeOf((*MockCategoryServiceInterface)(nil).CategoryFromMCC), mccCode)
}

// FuzzyMatchMerchant mocks base method.
func (m *MockCategoryServiceInterface) FuzzyMatchMerchant(input string) (string, float64) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FuzzyMatchMerchant", input)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(float64)
	return ret0, ret1
}

// FuzzyMatchMerchant indicates an expected call of FuzzyMatchMerchant.
func (mr *MockCategoryServiceInterfaceMockRecorder) FuzzyMatchMerchant(input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FuzzyMatchMerchant", reflect.TypeOf((*MockCategoryServiceInterface)(nil).FuzzyMatchMerchant), input)
}

// OverrideCategory mocks base method.
func (m *MockCategoryServiceInterface) OverrideCategory(transaction *models.Transaction, newCategory, reason string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OverrideCategory", transaction, newCategory, reason)
	ret0, _ := ret[0].(error)
	return ret0
}

// OverrideCategory indicates an expected call of OverrideCategory.
func (mr *MockCategoryServiceInterfaceMockRecorder) OverrideCategory(transaction, newCategory, reason interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OverrideCategory", reflect.TypeOf((*MockCategoryServiceInterface)(nil).OverrideCategory), transaction, newCategory, reason)
}

// MockCustomerProfileServiceInterface is a mock of CustomerProfileServiceInterface interface.
type MockCustomerProfileServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockCustomerProfileServiceInterfaceMockRecorder
}

// MockCustomerProfileServiceInterfaceMockRecorder is the mock recorder for MockCustomerProfileServiceInterface.
type MockCustomerProfileServiceInterfaceMockRecorder struct {
	mock *MockCustomerProfileServiceInterface
}

// NewMockCustomerProfileServiceInterface creates a new mock instance.
func NewMockCustomerProfileServiceInterface(ctrl *gomock.Controller) *MockCustomerProfileServiceInterface {
	mock := &MockCustomerProfileServiceInterface{ctrl: ctrl}
	mock.recorder = &MockCustomerProfileServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCustomerProfileServiceInterface) EXPECT() *MockCustomerProfileServiceInterfaceMockRecorder {
	return m.recorder
}

// CreateCustomer mocks base method.
func (m *MockCustomerProfileServiceInterface) CreateCustomer(email, firstName, lastName, role string) (*models.User, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCustomer", email, firstName, lastName, role)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CreateCustomer indicates an expected call of CreateCustomer.
func (mr *MockCustomerProfileServiceInterfaceMockRecorder) CreateCustomer(email, firstName, lastName, role interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCustomer", reflect.TypeOf((*MockCustomerProfileServiceInterface)(nil).CreateCustomer), email, firstName, lastName, role)
}

// DeleteCustomer mocks base method.
func (m *MockCustomerProfileServiceInterface) DeleteCustomer(customerID uuid.UUID, reason string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCustomer", customerID, reason)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCustomer indicates an expected call of DeleteCustomer.
func (mr *MockCustomerProfileServiceInterfaceMockRecorder) DeleteCustomer(customerID, reason interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCustomer", reflect.TypeOf((*MockCustomerProfileServiceInterface)(nil).DeleteCustomer), customerID, reason)
}

// GetCustomerProfile mocks base method.
func (m *MockCustomerProfileServiceInterface) GetCustomerProfile(customerID uuid.UUID) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCustomerProfile", customerID)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCustomerProfile indicates an expected call of GetCustomerProfile.
func (mr *MockCustomerProfileServiceInterfaceMockRecorder) GetCustomerProfile(customerID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCustomerProfile", reflect.TypeOf((*MockCustomerProfileServiceInterface)(nil).GetCustomerProfile), customerID)
}

// UpdateCustomerEmail mocks base method.
func (m *MockCustomerProfileServiceInterface) UpdateCustomerEmail(customerID uuid.UUID, newEmail string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCustomerEmail", customerID, newEmail)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCustomerEmail indicates an expected call of UpdateCustomerEmail.
func (mr *MockCustomerProfileServiceInterfaceMockRecorder) UpdateCustomerEmail(customerID, newEmail interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCustomerEmail", reflect.TypeOf((*MockCustomerProfileServiceInterface)(nil).UpdateCustomerEmail), customerID, newEmail)
}

// UpdateCustomerProfile mocks base method.
func (m *MockCustomerProfileServiceInterface) UpdateCustomerProfile(customerID uuid.UUID, updates map[string]interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCustomerProfile", customerID, updates)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCustomerProfile indicates an expected call of UpdateCustomerProfile.
func (mr *MockCustomerProfileServiceInterfaceMockRecorder) UpdateCustomerProfile(customerID, updates interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCustomerProfile", reflect.TypeOf((*MockCustomerProfileServiceInterface)(nil).UpdateCustomerProfile), customerID, updates)
}

// MockCustomerSearchServiceInterface is a mock of CustomerSearchServiceInterface interface.
type MockCustomerSearchServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockCustomerSearchServiceInterfaceMockRecorder
}

// MockCustomerSearchServiceInterfaceMockRecorder is the mock recorder for MockCustomerSearchServiceInterface.
type MockCustomerSearchServiceInterfaceMockRecorder struct {
	mock *MockCustomerSearchServiceInterface
}

// NewMockCustomerSearchServiceInterface creates a new mock instance.
func NewMockCustomerSearchServiceInterface(ctrl *gomock.Controller) *MockCustomerSearchServiceInterface {
	mock := &MockCustomerSearchServiceInterface{ctrl: ctrl}
	mock.recorder = &MockCustomerSearchServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCustomerSearchServiceInterface) EXPECT() *MockCustomerSearchServiceInterfaceMockRecorder {
	return m.recorder
}

// SearchCustomers mocks base method.
func (m *MockCustomerSearchServiceInterface) SearchCustomers(query string, searchType models.SearchType, offset, limit int) ([]*models.CustomerSearchResult, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchCustomers", query, searchType, offset, limit)
	ret0, _ := ret[0].([]*models.CustomerSearchResult)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SearchCustomers indicates an expected call of SearchCustomers.
func (mr *MockCustomerSearchServiceInterfaceMockRecorder) SearchCustomers(query, searchType, offset, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchCustomers", reflect.TypeOf((*MockCustomerSearchServiceInterface)(nil).SearchCustomers), query, searchType, offset, limit)
}

// MockAccountMetricsServiceInterface is a mock of AccountMetricsServiceInterface interface.
type MockAccountMetricsServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockAccountMetricsServiceInterfaceMockRecorder
}

// MockAccountMetricsServiceInterfaceMockRecorder is the mock recorder for MockAccountMetricsServiceInterface.
type MockAccountMetricsServiceInterfaceMockRecorder struct {
	mock *MockAccountMetricsServiceInterface
}

// NewMockAccountMetricsServiceInterface creates a new mock instance.
func NewMockAccountMetricsServiceInterface(ctrl *gomock.Controller) *MockAccountMetricsServiceInterface {
	mock := &MockAccountMetricsServiceInterface{ctrl: ctrl}
	mock.recorder = &MockAccountMetricsServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccountMetricsServiceInterface) EXPECT() *MockAccountMetricsServiceInterfaceMockRecorder {
	return m.recorder
}

// GetAccountMetrics mocks base method.
func (m *MockAccountMetricsServiceInterface) GetAccountMetrics(requestorID, accountID uuid.UUID, startDate, endDate *time.Time, isAdmin bool) (*models.AccountMetrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountMetrics", requestorID, accountID, startDate, endDate, isAdmin)
	ret0, _ := ret[0].(*models.AccountMetrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountMetrics indicates an expected call of GetAccountMetrics.
func (mr *MockAccountMetricsServiceInterfaceMockRecorder) GetAccountMetrics(requestorID, accountID, startDate, endDate, isAdmin interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountMetrics", reflect.TypeOf((*MockAccountMetricsServiceInterface)(nil).GetAccountMetrics), requestorID, accountID, startDate, endDate, isAdmin)
}

// GetUserAggregateMetrics mocks base method.
func (m *MockAccountMetricsServiceInterface) GetUserAggregateMetrics(requestorID, targetUserID uuid.UUID, startDate, endDate *time.Time, isAdmin bool) (*models.UserAggregateMetrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserAggregateMetrics", requestorID, targetUserID, startDate, endDate, isAdmin)
	ret0, _ := ret[0].(*models.UserAggregateMetrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserAggregateMetrics indicates an expected call of GetUserAggregateMetrics.
func (mr *MockAccountMetricsServiceInterfaceMockRecorder) GetUserAggregateMetrics(requestorID, targetUserID, startDate, endDate, isAdmin interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserAggregateMetrics", reflect.TypeOf((*MockAccountMetricsServiceInterface)(nil).GetUserAggregateMetrics), requestorID, targetUserID, startDate, endDate, isAdmin)
}

// MockMetricsRecorderInterface is a mock of MetricsRecorderInterface interface.
type MockMetricsRecorderInterface struct {
	ctrl     *gomock.Controller
	recorder *MockMetricsRecorderInterfaceMockRecorder
}

// MockMetricsRecorderInterfaceMockRecorder is the mock recorder for MockMetricsRecorderInterface.
type MockMetricsRecorderInterfaceMockRecorder struct {
	mock *MockMetricsRecorderInterface
}

// NewMockMetricsRecorderInterface creates a new mock instance.
func NewMockMetricsRecorderInterface(ctrl *gomock.Controller) *MockMetricsRecorderInterface {
	mock := &MockMetricsRecorderInterface{ctrl: ctrl}
	mock.recorder = &MockMetricsRecorderInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetricsRecorderInterface) EXPECT() *MockMetricsRecorderInterfaceMockRecorder {
	return m.recorder
}

// IncrementCounter mocks base method.
func (m *MockMetricsRecorderInterface) IncrementCounter(name string, tags map[string]string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IncrementCounter", name, tags)
}

// IncrementCounter indicates an expected call of IncrementCounter.
func (mr *MockMetricsRecorderInterfaceMockRecorder) IncrementCounter(name, tags interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementCounter", reflect.TypeOf((*MockMetricsRecorderInterface)(nil).IncrementCounter), name, tags)
}

// RecordGauge mocks base method.
func (m *MockMetricsRecorderInterface) RecordGauge(name string, value float64, tags map[string]string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecordGauge", name, value, tags)
}

// RecordGauge indicates an expected call of RecordGauge.
func (mr *MockMetricsRecorderInterfaceMockRecorder) RecordGauge(name, value, tags interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordGauge", reflect.TypeOf((*MockMetricsRecorderInterface)(nil).RecordGauge), name, value, tags)
}

// RecordProcessingTime mocks base method.
func (m *MockMetricsRecorderInterface) RecordProcessingTime(name string, duration time.Duration) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecordProcessingTime", name, duration)
}

// RecordProcessingTime indicates an expected call of RecordProcessingTime.
func (mr *MockMetricsRecorderInterfaceMockRecorder) RecordProcessingTime(name, duration interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordProcessingTime", reflect.TypeOf((*MockMetricsRecorderInterface)(nil).RecordProcessingTime), name, duration)
}

// MockStatementServiceInterface is a mock of StatementServiceInterface interface.
type MockStatementServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockStatementServiceInterfaceMockRecorder
}

// MockStatementServiceInterfaceMockRecorder is the mock recorder for MockStatementServiceInterface.
type MockStatementServiceInterfaceMockRecorder struct {
	mock *MockStatementServiceInterface
}

// NewMockStatementServiceInterface creates a new mock instance.
func NewMockStatementServiceInterface(ctrl *gomock.Controller) *MockStatementServiceInterface {
	mock := &MockStatementServiceInterface{ctrl: ctrl}
	mock.recorder = &MockStatementServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStatementServiceInterface) EXPECT() *MockStatementServiceInterfaceMockRecorder {
	return m.recorder
}

// GenerateStatement mocks base method.
func (m *MockStatementServiceInterface) GenerateStatement(requestorID, accountID uuid.UUID, periodType string, year, period int, isAdmin bool) (*models.AccountStatement, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateStatement", requestorID, accountID, periodType, year, period, isAdmin)
	ret0, _ := ret[0].(*models.AccountStatement)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateStatement indicates an expected call of GenerateStatement.
func (mr *MockStatementServiceInterfaceMockRecorder) GenerateStatement(requestorID, accountID, periodType, year, period, isAdmin interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateStatement", reflect.TypeOf((*MockStatementServiceInterface)(nil).GenerateStatement), requestorID, accountID, periodType, year, period, isAdmin)
}

// MockTransactionGeneratorInterface is a mock of TransactionGeneratorInterface interface.
type MockTransactionGeneratorInterface struct {
	ctrl     *gomock.Controller
	recorder *MockTransactionGeneratorInterfaceMockRecorder
}

// MockTransactionGeneratorInterfaceMockRecorder is the mock recorder for MockTransactionGeneratorInterface.
type MockTransactionGeneratorInterfaceMockRecorder struct {
	mock *MockTransactionGeneratorInterface
}

// NewMockTransactionGeneratorInterface creates a new mock instance.
func NewMockTransactionGeneratorInterface(ctrl *gomock.Controller) *MockTransactionGeneratorInterface {
	mock := &MockTransactionGeneratorInterface{ctrl: ctrl}
	mock.recorder = &MockTransactionGeneratorInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransactionGeneratorInterface) EXPECT() *MockTransactionGeneratorInterfaceMockRecorder {
	return m.recorder
}

// GenerateAmount mocks base method.
func (m *MockTransactionGeneratorInterface) GenerateAmount(category string) decimal.Decimal {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateAmount", category)
	ret0, _ := ret[0].(decimal.Decimal)
	return ret0
}

// GenerateAmount indicates an expected call of GenerateAmount.
func (mr *MockTransactionGeneratorInterfaceMockRecorder) GenerateAmount(category interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateAmount", reflect.TypeOf((*MockTransactionGeneratorInterface)(nil).GenerateAmount), category)
}

// GenerateBillTransactions mocks base method.
func (m *MockTransactionGeneratorInterface) GenerateBillTransactions(accountID uuid.UUID, startDate, endDate time.Time, startingBalance decimal.Decimal) []*models.Transaction {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateBillTransactions", accountID, startDate, endDate, startingBalance)
	ret0, _ := ret[0].([]*models.Transaction)
	return ret0
}

// GenerateBillTransactions indicates an expected call of GenerateBillTransactions.
func (mr *MockTransactionGeneratorInterfaceMockRecorder) GenerateBillTransactions(accountID, startDate, endDate, startingBalance interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateBillTransactions", reflect.TypeOf((*MockTransactionGeneratorInterface)(nil).GenerateBillTransactions), accountID, startDate, endDate, startingBalance)
}

// GenerateDailyPurchases mocks base method.
func (m *MockTransactionGeneratorInterface) GenerateDailyPurchases(accountID uuid.UUID, startDate, endDate time.Time, startingBalance decimal.Decimal) []*models.Transaction {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateDailyPurchases", accountID, startDate, endDate, startingBalance)
	ret0, _ := ret[0].([]*models.Transaction)
	return ret0
}

// GenerateDailyPurchases indicates an expected call of GenerateDailyPurchases.
func (mr *MockTransactionGeneratorInterfaceMockRecorder) GenerateDailyPurchases(accountID, startDate, endDate, startingBalance interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateDailyPurchases", reflect.TypeOf((*MockTransactionGeneratorInterface)(nil).GenerateDailyPurchases), accountID, startDate, endDate, startingBalance)
}

// GenerateFeeAmount mocks base method.
func (m *MockTransactionGeneratorInterface) GenerateFeeAmount() decimal.Decimal {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateFeeAmount")
	ret0, _ := ret[0].(decimal.Decimal)
	return ret0
}

// GenerateFeeAmount indicates an expected call of GenerateFeeAmount.
func (mr *MockTransactionGeneratorInterfaceMockRecorder) GenerateFeeAmount() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateFeeAmount", reflect.TypeOf((*MockTransactionGeneratorInterface)(nil).GenerateFeeAmount))
}

// GenerateHistoricalTransactions mocks base method.
func (m *MockTransactionGeneratorInterface) GenerateHistoricalTransactions(accountID uuid.UUID, startDate, endDate time.Time, startingBalance decimal.Decimal, count int) []*models.Transaction {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateHistoricalTransactions", accountID, startDate, endDate, startingBalance, count)
	ret0, _ := ret[0].([]*models.Transaction)
	return ret0
}

// GenerateHistoricalTransactions indicates an expected call of GenerateHistoricalTransactions.
func (mr *MockTransactionGeneratorInterfaceMockRecorder) GenerateHistoricalTransactions(accountID, startDate, endDate, startingBalance, count interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateHistoricalTransactions", reflect.TypeOf((*MockTransactionGeneratorInterface)(nil).GenerateHistoricalTransactions), accountID, startDate, endDate, startingBalance, count)
}

// GenerateSalaryTransactions mocks base method.
func (m *MockTransactionGeneratorInterface) GenerateSalaryTransactions(accountID uuid.UUID, startDate, endDate time.Time, startingBalance decimal.Decimal) []*models.Transaction {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateSalaryTransactions", accountID, startDate, endDate, startingBalance)
	ret0, _ := ret[0].([]*models.Transaction)
	return ret0
}

// GenerateSalaryTransactions indicates an expected call of GenerateSalaryTransactions.
func (mr *MockTransactionGeneratorInterfaceMockRecorder) GenerateSalaryTransactions(accountID, startDate, endDate, startingBalance interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateSalaryTransactions", reflect.TypeOf((*MockTransactionGeneratorInterface)(nil).GenerateSalaryTransactions), accountID, startDate, endDate, startingBalance)
}

// GenerateTimestamp mocks base method.
func (m *MockTransactionGeneratorInterface) GenerateTimestamp(startDate, endDate time.Time) time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateTimestamp", startDate, endDate)
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// GenerateTimestamp indicates an expected call of GenerateTimestamp.
func (mr *MockTransactionGeneratorInterfaceMockRecorder) GenerateTimestamp(startDate, endDate interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateTimestamp", reflect.TypeOf((*MockTransactionGeneratorInterface)(nil).GenerateTimestamp), startDate, endDate)
}

// GenerateTransactionType mocks base method.
func (m *MockTransactionGeneratorInterface) GenerateTransactionType() (string, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateTransactionType")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GenerateTransactionType indicates an expected call of GenerateTransactionType.
func (mr *MockTransactionGeneratorInterfaceMockRecorder) GenerateTransactionType() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateTransactionType", reflect.TypeOf((*MockTransactionGeneratorInterface)(nil).GenerateTransactionType))
}

// GetMerchantPool mocks base method.
func (m *MockTransactionGeneratorInterface) GetMerchantPool() []models.MerchantInfo {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMerchantPool")
	ret0, _ := ret[0].([]models.MerchantInfo)
	return ret0
}

// GetMerchantPool indicates an expected call of GetMerchantPool.
func (mr *MockTransactionGeneratorInterfaceMockRecorder) GetMerchantPool() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMerchantPool", reflect.TypeOf((*MockTransactionGeneratorInterface)(nil).GetMerchantPool))
}

// SelectRandomMerchant mocks base method.
func (m *MockTransactionGeneratorInterface) SelectRandomMerchant() models.MerchantInfo {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectRandomMerchant")
	ret0, _ := ret[0].(models.MerchantInfo)
	return ret0
}

// SelectRandomMerchant indicates an expected call of SelectRandomMerchant.
func (mr *MockTransactionGeneratorInterfaceMockRecorder) SelectRandomMerchant() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectRandomMerchant", reflect.TypeOf((*MockTransactionGeneratorInterface)(nil).SelectRandomMerchant))
}

// MockAuthServiceInterface is a mock of AuthServiceInterface interface.
type MockAuthServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockAuthServiceInterfaceMockRecorder
}

// MockAuthServiceInterfaceMockRecorder is the mock recorder for MockAuthServiceInterface.
type MockAuthServiceInterfaceMockRecorder struct {
	mock *MockAuthServiceInterface
}

// NewMockAuthServiceInterface creates a new mock instance.
func NewMockAuthServiceInterface(ctrl *gomock.Controller) *MockAuthServiceInterface {
	mock := &MockAuthServiceInterface{ctrl: ctrl}
	mock.recorder = &MockAuthServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthServiceInterface) EXPECT() *MockAuthServiceInterfaceMockRecorder {
	return m.recorder
}

// Login mocks base method.
func (m *MockAuthServiceInterface) Login(req *dto.LoginRequest, ipAddress, userAgent string) (*dto.TokenResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", req, ipAddress, userAgent)
	ret0, _ := ret[0].(*dto.TokenResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockAuthServiceInterfaceMockRecorder) Login(req, ipAddress, userAgent interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockAuthServiceInterface)(nil).Login), req, ipAddress, userAgent)
}

// Logout mocks base method.
func (m *MockAuthServiceInterface) Logout(accessToken, ipAddress, userAgent string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logout", accessToken, ipAddress, userAgent)
	ret0, _ := ret[0].(error)
	return ret0
}

// Logout indicates an expected call of Logout.
func (mr *MockAuthServiceInterfaceMockRecorder) Logout(accessToken, ipAddress, userAgent interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logout", reflect.TypeOf((*MockAuthServiceInterface)(nil).Logout), accessToken, ipAddress, userAgent)
}

// RefreshTokens mocks base method.
func (m *MockAuthServiceInterface) RefreshTokens(refreshToken, ipAddress, userAgent string) (*dto.TokenResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshTokens", refreshToken, ipAddress, userAgent)
	ret0, _ := ret[0].(*dto.TokenResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RefreshTokens indicates an expected call of RefreshTokens.
func (mr *MockAuthServiceInterfaceMockRecorder) RefreshTokens(refreshToken, ipAddress, userAgent interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshTokens", reflect.TypeOf((*MockAuthServiceInterface)(nil).RefreshTokens), refreshToken, ipAddress, userAgent)
}

// Register mocks base method.
func (m *MockAuthServiceInterface) Register(req *dto.RegisterRequest, ipAddress, userAgent string) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", req, ipAddress, userAgent)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Register indicates an expected call of Register.
func (mr *MockAuthServiceInterfaceMockRecorder) Register(req, ipAddress, userAgent interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockAuthServiceInterface)(nil).Register), req, ipAddress, userAgent)
}

// MockTokenServiceInterface is a mock of TokenServiceInterface interface.
type MockTokenServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockTokenServiceInterfaceMockRecorder
}

// MockTokenServiceInterfaceMockRecorder is the mock recorder for MockTokenServiceInterface.
type MockTokenServiceInterfaceMockRecorder struct {
	mock *MockTokenServiceInterface
}

// NewMockTokenServiceInterface creates a new mock instance.
func NewMockTokenServiceInterface(ctrl *gomock.Controller) *MockTokenServiceInterface {
	mock := &MockTokenServiceInterface{ctrl: ctrl}
	mock.recorder = &MockTokenServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenServiceInterface) EXPECT() *MockTokenServiceInterfaceMockRecorder {
	return m.recorder
}

// ExtractTokenFromHeader mocks base method.
func (m *MockTokenServiceInterface) ExtractTokenFromHeader(authHeader string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExtractTokenFromHeader", authHeader)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExtractTokenFromHeader indicates an expected call of ExtractTokenFromHeader.
func (mr *MockTokenServiceInterfaceMockRecorder) ExtractTokenFromHeader(authHeader interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExtractTokenFromHeader", reflect.TypeOf((*MockTokenServiceInterface)(nil).ExtractTokenFromHeader), authHeader)
}

// GenerateAccessToken mocks base method.
func (m *MockTokenServiceInterface) GenerateAccessToken(user *models.User) (string, time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateAccessToken", user)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(time.Time)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GenerateAccessToken indicates an expected call of GenerateAccessToken.
func (mr *MockTokenServiceInterfaceMockRecorder) GenerateAccessToken(user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateAccessToken", reflect.TypeOf((*MockTokenServiceInterface)(nil).GenerateAccessToken), user)
}

// GenerateRefreshToken mocks base method.
func (m *MockTokenServiceInterface) GenerateRefreshToken(userID uuid.UUID) (string, time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateRefreshToken", userID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(time.Time)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GenerateRefreshToken indicates an expected call of GenerateRefreshToken.
func (mr *MockTokenServiceInterfaceMockRecorder) GenerateRefreshToken(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateRefreshToken", reflect.TypeOf((*MockTokenServiceInterface)(nil).GenerateRefreshToken), userID)
}

// GetJTI mocks base method.
func (m *MockTokenServiceInterface) GetJTI(tokenString string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJTI", tokenString)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetJTI indicates an expected call of GetJTI.
func (mr *MockTokenServiceInterfaceMockRecorder) GetJTI(tokenString interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJTI", reflect.TypeOf((*MockTokenServiceInterface)(nil).GetJTI), tokenString)
}

// GetTokenExpiry mocks base method.
func (m *MockTokenServiceInterface) GetTokenExpiry(tokenString string) (time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTokenExpiry", tokenString)
	ret0, _ := ret[0].(time.Time)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTokenExpiry indicates an expected call of GetTokenExpiry.
func (mr *MockTokenServiceInterfaceMockRecorder) GetTokenExpiry(tokenString interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTokenExpiry", reflect.TypeOf((*MockTokenServiceInterface)(nil).GetTokenExpiry), tokenString)
}

// ValidateAccessToken mocks base method.
func (m *MockTokenServiceInterface) ValidateAccessToken(tokenString string) (*models.CustomClaims, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateAccessToken", tokenString)
	ret0, _ := ret[0].(*models.CustomClaims)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateAccessToken indicates an expected call of ValidateAccessToken.
func (mr *MockTokenServiceInterfaceMockRecorder) ValidateAccessToken(tokenString interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateAccessToken", reflect.TypeOf((*MockTokenServiceInterface)(nil).ValidateAccessToken), tokenString)
}

// ValidateRefreshToken mocks base method.
func (m *MockTokenServiceInterface) ValidateRefreshToken(tokenString string) (*models.CustomClaims, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateRefreshToken", tokenString)
	ret0, _ := ret[0].(*models.CustomClaims)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateRefreshToken indicates an expected call of ValidateRefreshToken.
func (mr *MockTokenServiceInterfaceMockRecorder) ValidateRefreshToken(tokenString interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateRefreshToken", reflect.TypeOf((*MockTokenServiceInterface)(nil).ValidateRefreshToken), tokenString)
}

// MockPasswordServiceInterface is a mock of PasswordServiceInterface interface.
type MockPasswordServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockPasswordServiceInterfaceMockRecorder
}

// MockPasswordServiceInterfaceMockRecorder is the mock recorder for MockPasswordServiceInterface.
type MockPasswordServiceInterfaceMockRecorder struct {
	mock *MockPasswordServiceInterface
}

// NewMockPasswordServiceInterface creates a new mock instance.
func NewMockPasswordServiceInterface(ctrl *gomock.Controller) *MockPasswordServiceInterface {
	mock := &MockPasswordServiceInterface{ctrl: ctrl}
	mock.recorder = &MockPasswordServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPasswordServiceInterface) EXPECT() *MockPasswordServiceInterfaceMockRecorder {
	return m.recorder
}

// AdminResetPassword mocks base method.
func (m *MockPasswordServiceInterface) AdminResetPassword(customerID, adminID uuid.UUID) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AdminResetPassword", customerID, adminID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AdminResetPassword indicates an expected call of AdminResetPassword.
func (mr *MockPasswordServiceInterfaceMockRecorder) AdminResetPassword(customerID, adminID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdminResetPassword", reflect.TypeOf((*MockPasswordServiceInterface)(nil).AdminResetPassword), customerID, adminID)
}

// ComparePassword mocks base method.
func (m *MockPasswordServiceInterface) ComparePassword(password, hash string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ComparePassword", password, hash)
	ret0, _ := ret[0].(bool)
	return ret0
}

// ComparePassword indicates an expected call of ComparePassword.
func (mr *MockPasswordServiceInterfaceMockRecorder) ComparePassword(password, hash interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ComparePassword", reflect.TypeOf((*MockPasswordServiceInterface)(nil).ComparePassword), password, hash)
}

// CustomerUpdatePassword mocks base method.
func (m *MockPasswordServiceInterface) CustomerUpdatePassword(customerID uuid.UUID, currentPassword, newPassword string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CustomerUpdatePassword", customerID, currentPassword, newPassword)
	ret0, _ := ret[0].(error)
	return ret0
}

// CustomerUpdatePassword indicates an expected call of CustomerUpdatePassword.
func (mr *MockPasswordServiceInterfaceMockRecorder) CustomerUpdatePassword(customerID, currentPassword, newPassword interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CustomerUpdatePassword", reflect.TypeOf((*MockPasswordServiceInterface)(nil).CustomerUpdatePassword), customerID, currentPassword, newPassword)
}

// GenerateSecurePassword mocks base method.
func (m *MockPasswordServiceInterface) GenerateSecurePassword() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateSecurePassword")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateSecurePassword indicates an expected call of GenerateSecurePassword.
func (mr *MockPasswordServiceInterfaceMockRecorder) GenerateSecurePassword() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateSecurePassword", reflect.TypeOf((*MockPasswordServiceInterface)(nil).GenerateSecurePassword))
}

// GenerateSecurePasswordWithLength mocks base method.
func (m *MockPasswordServiceInterface) GenerateSecurePasswordWithLength(length int) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateSecurePasswordWithLength", length)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateSecurePasswordWithLength indicates an expected call of GenerateSecurePasswordWithLength.
func (mr *MockPasswordServiceInterfaceMockRecorder) GenerateSecurePasswordWithLength(length interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateSecurePasswordWithLength", reflect.TypeOf((*MockPasswordServiceInterface)(nil).GenerateSecurePasswordWithLength), length)
}

// HashPassword mocks base method.
func (m *MockPasswordServiceInterface) HashPassword(password string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HashPassword", password)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HashPassword indicates an expected call of HashPassword.
func (mr *MockPasswordServiceInterfaceMockRecorder) HashPassword(password interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HashPassword", reflect.TypeOf((*MockPasswordServiceInterface)(nil).HashPassword), password)
}

// HashPasswordWithoutValidation mocks base method.
func (m *MockPasswordServiceInterface) HashPasswordWithoutValidation(password string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HashPasswordWithoutValidation", password)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HashPasswordWithoutValidation indicates an expected call of HashPasswordWithoutValidation.
func (mr *MockPasswordServiceInterfaceMockRecorder) HashPasswordWithoutValidation(password interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HashPasswordWithoutValidation", reflect.TypeOf((*MockPasswordServiceInterface)(nil).HashPasswordWithoutValidation), password)
}

// PasswordStrength mocks base method.
func (m *MockPasswordServiceInterface) PasswordStrength(password string) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PasswordStrength", password)
	ret0, _ := ret[0].(int)
	return ret0
}

// PasswordStrength indicates an expected call of PasswordStrength.
func (mr *MockPasswordServiceInterfaceMockRecorder) PasswordStrength(password interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PasswordStrength", reflect.TypeOf((*MockPasswordServiceInterface)(nil).PasswordStrength), password)
}

// ValidatePassword mocks base method.
func (m *MockPasswordServiceInterface) ValidatePassword(password string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidatePassword", password)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidatePassword indicates an expected call of ValidatePassword.
func (mr *MockPasswordServiceInterfaceMockRecorder) ValidatePassword(password interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidatePassword", reflect.TypeOf((*MockPasswordServiceInterface)(nil).ValidatePassword), password)
}

// MockAuditLoggerInterface is a mock of AuditLoggerInterface interface.
type MockAuditLoggerInterface struct {
	ctrl     *gomock.Controller
	recorder *MockAuditLoggerInterfaceMockRecorder
}

// MockAuditLoggerInterfaceMockRecorder is the mock recorder for MockAuditLoggerInterface.
type MockAuditLoggerInterfaceMockRecorder struct {
	mock *MockAuditLoggerInterface
}

// NewMockAuditLoggerInterface creates a new mock instance.
func NewMockAuditLoggerInterface(ctrl *gomock.Controller) *MockAuditLoggerInterface {
	mock := &MockAuditLoggerInterface{ctrl: ctrl}
	mock.recorder = &MockAuditLoggerInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuditLoggerInterface) EXPECT() *MockAuditLoggerInterfaceMockRecorder {
	return m.recorder
}

// LogBalanceUpdate mocks base method.
func (m *MockAuditLoggerInterface) LogBalanceUpdate(ctx context.Context, accountID uuid.UUID, oldBalance, newBalance string, transactionID uuid.UUID) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "LogBalanceUpdate", ctx, accountID, oldBalance, newBalance, transactionID)
}

// LogBalanceUpdate indicates an expected call of LogBalanceUpdate.
func (mr *MockAuditLoggerInterfaceMockRecorder) LogBalanceUpdate(ctx, accountID, oldBalance, newBalance, transactionID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogBalanceUpdate", reflect.TypeOf((*MockAuditLoggerInterface)(nil).LogBalanceUpdate), ctx, accountID, oldBalance, newBalance, transactionID)
}

// LogCircuitBreakerStateChange mocks base method.
func (m *MockAuditLoggerInterface) LogCircuitBreakerStateChange(ctx context.Context, service, oldState, newState string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "LogCircuitBreakerStateChange", ctx, service, oldState, newState)
}

// LogCircuitBreakerStateChange indicates an expected call of LogCircuitBreakerStateChange.
func (mr *MockAuditLoggerInterfaceMockRecorder) LogCircuitBreakerStateChange(ctx, service, oldState, newState interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogCircuitBreakerStateChange", reflect.TypeOf((*MockAuditLoggerInterface)(nil).LogCircuitBreakerStateChange), ctx, service, oldState, newState)
}

// LogOptimisticLockConflict mocks base method.
func (m *MockAuditLoggerInterface) LogOptimisticLockConflict(ctx context.Context, entityType string, entityID uuid.UUID, expectedVersion, actualVersion int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "LogOptimisticLockConflict", ctx, entityType, entityID, expectedVersion, actualVersion)
}

// LogOptimisticLockConflict indicates an expected call of LogOptimisticLockConflict.
func (mr *MockAuditLoggerInterfaceMockRecorder) LogOptimisticLockConflict(ctx, entityType, entityID, expectedVersion, actualVersion interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogOptimisticLockConflict", reflect.TypeOf((*MockAuditLoggerInterface)(nil).LogOptimisticLockConflict), ctx, entityType, entityID, expectedVersion, actualVersion)
}

// LogQueueItemEnqueued mocks base method.
func (m *MockAuditLoggerInterface) LogQueueItemEnqueued(ctx context.Context, queueItemID, transactionID uuid.UUID, operation string, priority int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "LogQueueItemEnqueued", ctx, queueItemID, transactionID, operation, priority)
}

// LogQueueItemEnqueued indicates an expected call of LogQueueItemEnqueued.
func (mr *MockAuditLoggerInterfaceMockRecorder) LogQueueItemEnqueued(ctx, queueItemID, transactionID, operation, priority interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogQueueItemEnqueued", reflect.TypeOf((*MockAuditLoggerInterface)(nil).LogQueueItemEnqueued), ctx, queueItemID, transactionID, operation, priority)
}

// LogQueueItemProcessed mocks base method.
func (m *MockAuditLoggerInterface) LogQueueItemProcessed(ctx context.Context, queueItemID, transactionID uuid.UUID, operation string, retryCount int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "LogQueueItemProcessed", ctx, queueItemID, transactionID, operation, retryCount)
}

// LogQueueItemProcessed indicates an expected call of LogQueueItemProcessed.
func (mr *MockAuditLoggerInterfaceMockRecorder) LogQueueItemProcessed(ctx, queueItemID, transactionID, operation, retryCount interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogQueueItemProcessed", reflect.TypeOf((*MockAuditLoggerInterface)(nil).LogQueueItemProcessed), ctx, queueItemID, transactionID, operation, retryCount)
}

// LogRetryAttempt mocks base method.
func (m *MockAuditLoggerInterface) LogRetryAttempt(ctx context.Context, queueItemID, transactionID uuid.UUID, retryCount, maxRetries int, backoffMs int64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "LogRetryAttempt", ctx, queueItemID, transactionID, retryCount, maxRetries, backoffMs)
}

// LogRetryAttempt indicates an expected call of LogRetryAttempt.
func (mr *MockAuditLoggerInterfaceMockRecorder) LogRetryAttempt(ctx, queueItemID, transactionID, retryCount, maxRetries, backoffMs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogRetryAttempt", reflect.TypeOf((*MockAuditLoggerInterface)(nil).LogRetryAttempt), ctx, queueItemID, transactionID, retryCount, maxRetries, backoffMs)
}

// LogTransactionProcessingCompleted mocks base method.
func (m *MockAuditLoggerInterface) LogTransactionProcessingCompleted(ctx context.Context, transactionID uuid.UUID, operation string, durationMs int64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "LogTransactionProcessingCompleted", ctx, transactionID, operation, durationMs)
}

// LogTransactionProcessingCompleted indicates an expected call of LogTransactionProcessingCompleted.
func (mr *MockAuditLoggerInterfaceMockRecorder) LogTransactionProcessingCompleted(ctx, transactionID, operation, durationMs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogTransactionProcessingCompleted", reflect.TypeOf((*MockAuditLoggerInterface)(nil).LogTransactionProcessingCompleted), ctx, transactionID, operation, durationMs)
}

// LogTransactionProcessingFailed mocks base method.
func (m *MockAuditLoggerInterface) LogTransactionProcessingFailed(ctx context.Context, transactionID uuid.UUID, operation, errorMsg string, retryCount int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "LogTransactionProcessingFailed", ctx, transactionID, operation, errorMsg, retryCount)
}

// LogTransactionProcessingFailed indicates an expected call of LogTransactionProcessingFailed.
func (mr *MockAuditLoggerInterfaceMockRecorder) LogTransactionProcessingFailed(ctx, transactionID, operation, errorMsg, retryCount interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogTransactionProcessingFailed", reflect.TypeOf((*MockAuditLoggerInterface)(nil).LogTransactionProcessingFailed), ctx, transactionID, operation, errorMsg, retryCount)
}

// LogTransactionProcessingStarted mocks base method.
func (m *MockAuditLoggerInterface) LogTransactionProcessingStarted(ctx context.Context, transactionID uuid.UUID, operation string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "LogTransactionProcessingStarted", ctx, transactionID, operation)
}

// LogTransactionProcessingStarted indicates an expected call of LogTransactionProcessingStarted.
func (mr *MockAuditLoggerInterfaceMockRecorder) LogTransactionProcessingStarted(ctx, transactionID, operation interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogTransactionProcessingStarted", reflect.TypeOf((*MockAuditLoggerInterface)(nil).LogTransactionProcessingStarted), ctx, transactionID, operation)
}

// LogTransactionStateChange mocks base method.
func (m *MockAuditLoggerInterface) LogTransactionStateChange(ctx context.Context, transactionID uuid.UUID, oldStatus, newStatus string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "LogTransactionStateChange", ctx, transactionID, oldStatus, newStatus)
}

// LogTransactionStateChange indicates an expected call of LogTransactionStateChange.
func (mr *MockAuditLoggerInterfaceMockRecorder) LogTransactionStateChange(ctx, transactionID, oldStatus, newStatus interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogTransactionStateChange", reflect.TypeOf((*MockAuditLoggerInterface)(nil).LogTransactionStateChange), ctx, transactionID, oldStatus, newStatus)
}

// LogTransferCompleted mocks base method.
func (m *MockAuditLoggerInterface) LogTransferCompleted(ctx context.Context, transferID uuid.UUID, durationMs int64, debitTxID, creditTxID *uuid.UUID) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "LogTransferCompleted", ctx, transferID, durationMs, debitTxID, creditTxID)
}

// LogTransferCompleted indicates an expected call of LogTransferCompleted.
func (mr *MockAuditLoggerInterfaceMockRecorder) LogTransferCompleted(ctx, transferID, durationMs, debitTxID, creditTxID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogTransferCompleted", reflect.TypeOf((*MockAuditLoggerInterface)(nil).LogTransferCompleted), ctx, transferID, durationMs, debitTxID, creditTxID)
}

// LogTransferFailed mocks base method.
func (m *MockAuditLoggerInterface) LogTransferFailed(ctx context.Context, transferID uuid.UUID, errorMsg string, durationMs int64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "LogTransferFailed", ctx, transferID, errorMsg, durationMs)
}

// LogTransferFailed indicates an expected call of LogTransferFailed.
func (mr *MockAuditLoggerInterfaceMockRecorder) LogTransferFailed(ctx, transferID, errorMsg, durationMs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogTransferFailed", reflect.TypeOf((*MockAuditLoggerInterface)(nil).LogTransferFailed), ctx, transferID, errorMsg, durationMs)
}

// LogTransferIdempotencyCheck mocks base method.
func (m *MockAuditLoggerInterface) LogTransferIdempotencyCheck(ctx context.Context, idempotencyKey string, existingTransferID uuid.UUID, status string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "LogTransferIdempotencyCheck", ctx, idempotencyKey, existingTransferID, status)
}

// LogTransferIdempotencyCheck indicates an expected call of LogTransferIdempotencyCheck.
func (mr *MockAuditLoggerInterfaceMockRecorder) LogTransferIdempotencyCheck(ctx, idempotencyKey, existingTransferID, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogTransferIdempotencyCheck", reflect.TypeOf((*MockAuditLoggerInterface)(nil).LogTransferIdempotencyCheck), ctx, idempotencyKey, existingTransferID, status)
}

// LogTransferInitiated mocks base method.
func (m *MockAuditLoggerInterface) LogTransferInitiated(ctx context.Context, transferID, fromAccountID, toAccountID uuid.UUID, amount, idempotencyKey string, userID uuid.UUID) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "LogTransferInitiated", ctx, transferID, fromAccountID, toAccountID, amount, idempotencyKey, userID)
}

// LogTransferInitiated indicates an expected call of LogTransferInitiated.
func (mr *MockAuditLoggerInterfaceMockRecorder) LogTransferInitiated(ctx, transferID, fromAccountID, toAccountID, amount, idempotencyKey, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogTransferInitiated", reflect.TypeOf((*MockAuditLoggerInterface)(nil).LogTransferInitiated), ctx, transferID, fromAccountID, toAccountID, amount, idempotencyKey, userID)
}

// MockCircuitBreakerInterface is a mock of CircuitBreakerInterface interface.
type MockCircuitBreakerInterface struct {
	ctrl     *gomock.Controller
	recorder *MockCircuitBreakerInterfaceMockRecorder
}

// MockCircuitBreakerInterfaceMockRecorder is the mock recorder for MockCircuitBreakerInterface.
type MockCircuitBreakerInterfaceMockRecorder struct {
	mock *MockCircuitBreakerInterface
}

// NewMockCircuitBreakerInterface creates a new mock instance.
func NewMockCircuitBreakerInterface(ctrl *gomock.Controller) *MockCircuitBreakerInterface {
	mock := &MockCircuitBreakerInterface{ctrl: ctrl}
	mock.recorder = &MockCircuitBreakerInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCircuitBreakerInterface) EXPECT() *MockCircuitBreakerInterfaceMockRecorder {
	return m.recorder
}

// GetFailureCount mocks base method.
func (m *MockCircuitBreakerInterface) GetFailureCount() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFailureCount")
	ret0, _ := ret[0].(int)
	return ret0
}

// GetFailureCount indicates an expected call of GetFailureCount.
func (mr *MockCircuitBreakerInterfaceMockRecorder) GetFailureCount() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFailureCount", reflect.TypeOf((*MockCircuitBreakerInterface)(nil).GetFailureCount))
}

// GetState mocks base method.
func (m *MockCircuitBreakerInterface) GetState() models.CircuitBreakerState {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetState")
	ret0, _ := ret[0].(models.CircuitBreakerState)
	return ret0
}

// GetState indicates an expected call of GetState.
func (mr *MockCircuitBreakerInterfaceMockRecorder) GetState() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetState", reflect.TypeOf((*MockCircuitBreakerInterface)(nil).GetState))
}

// IsOpen mocks base method.
func (m *MockCircuitBreakerInterface) IsOpen() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsOpen")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsOpen indicates an expected call of IsOpen.
func (mr *MockCircuitBreakerInterfaceMockRecorder) IsOpen() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsOpen", reflect.TypeOf((*MockCircuitBreakerInterface)(nil).IsOpen))
}

// RecordFailure mocks base method.
func (m *MockCircuitBreakerInterface) RecordFailure() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecordFailure")
}

// RecordFailure indicates an expected call of RecordFailure.
func (mr *MockCircuitBreakerInterfaceMockRecorder) RecordFailure() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordFailure", reflect.TypeOf((*MockCircuitBreakerInterface)(nil).RecordFailure))
}

// RecordSuccess mocks base method.
func (m *MockCircuitBreakerInterface) RecordSuccess() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecordSuccess")
}

// RecordSuccess indicates an expected call of RecordSuccess.
func (mr *MockCircuitBreakerInterfaceMockRecorder) RecordSuccess() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordSuccess", reflect.TypeOf((*MockCircuitBreakerInterface)(nil).RecordSuccess))
}

// Reset mocks base method.
func (m *MockCircuitBreakerInterface) Reset() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Reset")
}

// Reset indicates an expected call of Reset.
func (mr *MockCircuitBreakerInterfaceMockRecorder) Reset() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reset", reflect.TypeOf((*MockCircuitBreakerInterface)(nil).Reset))
}

// MockCustomerLoggerInterface is a mock of CustomerLoggerInterface interface.
type MockCustomerLoggerInterface struct {
	ctrl     *gomock.Controller
	recorder *MockCustomerLoggerInterfaceMockRecorder
}

// MockCustomerLoggerInterfaceMockRecorder is the mock recorder for MockCustomerLoggerInterface.
type MockCustomerLoggerInterfaceMockRecorder struct {
	mock *MockCustomerLoggerInterface
}

// NewMockCustomerLoggerInterface creates a new mock instance.
func NewMockCustomerLoggerInterface(ctrl *gomock.Controller) *MockCustomerLoggerInterface {
	mock := &MockCustomerLoggerInterface{ctrl: ctrl}
	mock.recorder = &MockCustomerLoggerInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCustomerLoggerInterface) EXPECT() *MockCustomerLoggerInterfaceMockRecorder {
	return m.recorder
}

// LogAccountCreatedForCustomer mocks base method.
func (m *MockCustomerLoggerInterface) LogAccountCreatedForCustomer(ctx context.Context, accountID, customerID, adminUserID uuid.UUID, accountNumber string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "LogAccountCreatedForCustomer", ctx, accountID, customerID, adminUserID, accountNumber)
}

// LogAccountCreatedForCustomer indicates an expected call of LogAccountCreatedForCustomer.
func (mr *MockCustomerLoggerInterfaceMockRecorder) LogAccountCreatedForCustomer(ctx, accountID, customerID, adminUserID, accountNumber interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogAccountCreatedForCustomer", reflect.TypeOf((*MockCustomerLoggerInterface)(nil).LogAccountCreatedForCustomer), ctx, accountID, customerID, adminUserID, accountNumber)
}

// LogAccountOwnershipTransferred mocks base method.
func (m *MockCustomerLoggerInterface) LogAccountOwnershipTransferred(ctx context.Context, accountID, fromCustomerID, toCustomerID, adminUserID uuid.UUID) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "LogAccountOwnershipTransferred", ctx, accountID, fromCustomerID, toCustomerID, adminUserID)
}

// LogAccountOwnershipTransferred indicates an expected call of LogAccountOwnershipTransferred.
func (mr *MockCustomerLoggerInterfaceMockRecorder) LogAccountOwnershipTransferred(ctx, accountID, fromCustomerID, toCustomerID, adminUserID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogAccountOwnershipTransferred", reflect.TypeOf((*MockCustomerLoggerInterface)(nil).LogAccountOwnershipTransferred), ctx, accountID, fromCustomerID, toCustomerID, adminUserID)
}

// LogAuthorizationFailure mocks base method.
func (m *MockCustomerLoggerInterface) LogAuthorizationFailure(ctx context.Context, operation string, userID uuid.UUID, requiredRole string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "LogAuthorizationFailure", ctx, operation, userID, requiredRole)
}

// LogAuthorizationFailure indicates an expected call of LogAuthorizationFailure.
func (mr *MockCustomerLoggerInterfaceMockRecorder) LogAuthorizationFailure(ctx, operation, userID, requiredRole interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogAuthorizationFailure", reflect.TypeOf((*MockCustomerLoggerInterface)(nil).LogAuthorizationFailure), ctx, operation, userID, requiredRole)
}

// LogCustomerCreated mocks base method.
func (m *MockCustomerLoggerInterface) LogCustomerCreated(ctx context.Context, customerID uuid.UUID, email string, adminUserID uuid.UUID) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "LogCustomerCreated", ctx, customerID, email, adminUserID)
}

// LogCustomerCreated indicates an expected call of LogCustomerCreated.
func (mr *MockCustomerLoggerInterfaceMockRecorder) LogCustomerCreated(ctx, customerID, email, adminUserID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogCustomerCreated", reflect.TypeOf((*MockCustomerLoggerInterface)(nil).LogCustomerCreated), ctx, customerID, email, adminUserID)
}

// LogCustomerDeleted mocks base method.
func (m *MockCustomerLoggerInterface) LogCustomerDeleted(ctx context.Context, customerID uuid.UUID, accountsDeactivated int, adminUserID uuid.UUID) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "LogCustomerDeleted", ctx, customerID, accountsDeactivated, adminUserID)
}

// LogCustomerDeleted indicates an expected call of LogCustomerDeleted.
func (mr *MockCustomerLoggerInterfaceMockRecorder) LogCustomerDeleted(ctx, customerID, accountsDeactivated, adminUserID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogCustomerDeleted", reflect.TypeOf((*MockCustomerLoggerInterface)(nil).LogCustomerDeleted), ctx, customerID, accountsDeactivated, adminUserID)
}

// LogCustomerEmailUpdated mocks base method.
func (m *MockCustomerLoggerInterface) LogCustomerEmailUpdated(ctx context.Context, customerID uuid.UUID, oldEmail, newEmail string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "LogCustomerEmailUpdated", ctx, customerID, oldEmail, newEmail)
}

// LogCustomerEmailUpdated indicates an expected call of LogCustomerEmailUpdated.
func (mr *MockCustomerLoggerInterfaceMockRecorder) LogCustomerEmailUpdated(ctx, customerID, oldEmail, newEmail interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogCustomerEmailUpdated", reflect.TypeOf((*MockCustomerLoggerInterface)(nil).LogCustomerEmailUpdated), ctx, customerID, oldEmail, newEmail)
}

// LogCustomerProfileUpdated mocks base method.
func (m *MockCustomerLoggerInterface) LogCustomerProfileUpdated(ctx context.Context, customerID uuid.UUID, updatedFields []string, adminUserID uuid.UUID) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "LogCustomerProfileUpdated", ctx, customerID, updatedFields, adminUserID)
}

// LogCustomerProfileUpdated indicates an expected call of LogCustomerProfileUpdated.
func (mr *MockCustomerLoggerInterfaceMockRecorder) LogCustomerProfileUpdated(ctx, customerID, updatedFields, adminUserID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogCustomerProfileUpdated", reflect.TypeOf((*MockCustomerLoggerInterface)(nil).LogCustomerProfileUpdated), ctx, customerID, updatedFields, adminUserID)
}

// LogCustomerSearchCompleted mocks base method.
func (m *MockCustomerLoggerInterface) LogCustomerSearchCompleted(ctx context.Context, resultsCount int, durationMs int64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "LogCustomerSearchCompleted", ctx, resultsCount, durationMs)
}

// LogCustomerSearchCompleted indicates an expected call of LogCustomerSearchCompleted.
func (mr *MockCustomerLoggerInterfaceMockRecorder) LogCustomerSearchCompleted(ctx, resultsCount, durationMs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogCustomerSearchCompleted", reflect.TypeOf((*MockCustomerLoggerInterface)(nil).LogCustomerSearchCompleted), ctx, resultsCount, durationMs)
}

// LogCustomerSearchFailed mocks base method.
func (m *MockCustomerLoggerInterface) LogCustomerSearchFailed(ctx context.Context, errorMsg string, durationMs int64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "LogCustomerSearchFailed", ctx, errorMsg, durationMs)
}

// LogCustomerSearchFailed indicates an expected call of LogCustomerSearchFailed.
func (mr *MockCustomerLoggerInterfaceMockRecorder) LogCustomerSearchFailed(ctx, errorMsg, durationMs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogCustomerSearchFailed", reflect.TypeOf((*MockCustomerLoggerInterface)(nil).LogCustomerSearchFailed), ctx, errorMsg, durationMs)
}

// LogCustomerSearchStarted mocks base method.
func (m *MockCustomerLoggerInterface) LogCustomerSearchStarted(ctx context.Context, query, searchType string, adminUserID uuid.UUID) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "LogCustomerSearchStarted", ctx, query, searchType, adminUserID)
}

// LogCustomerSearchStarted indicates an expected call of LogCustomerSearchStarted.
func (mr *MockCustomerLoggerInterfaceMockRecorder) LogCustomerSearchStarted(ctx, query, searchType, adminUserID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogCustomerSearchStarted", reflect.TypeOf((*MockCustomerLoggerInterface)(nil).LogCustomerSearchStarted), ctx, query, searchType, adminUserID)
}

// LogPasswordChanged mocks base method.
func (m *MockCustomerLoggerInterface) LogPasswordChanged(ctx context.Context, customerID uuid.UUID) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "LogPasswordChanged", ctx, customerID)
}

// LogPasswordChanged indicates an expected call of LogPasswordChanged.
func (mr *MockCustomerLoggerInterfaceMockRecorder) LogPasswordChanged(ctx, customerID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogPasswordChanged", reflect.TypeOf((*MockCustomerLoggerInterface)(nil).LogPasswordChanged), ctx, customerID)
}

// LogPasswordReset mocks base method.
func (m *MockCustomerLoggerInterface) LogPasswordReset(ctx context.Context, customerID, adminUserID uuid.UUID) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "LogPasswordReset", ctx, customerID, adminUserID)
}

// LogPasswordReset indicates an expected call of LogPasswordReset.
func (mr *MockCustomerLoggerInterfaceMockRecorder) LogPasswordReset(ctx, customerID, adminUserID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogPasswordReset", reflect.TypeOf((*MockCustomerLoggerInterface)(nil).LogPasswordReset), ctx, customerID, adminUserID)
}

// LogValidationFailure mocks base method.
func (m *MockCustomerLoggerInterface) LogValidationFailure(ctx context.Context, operation, errorMsg string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "LogValidationFailure", ctx, operation, errorMsg)
}

// LogValidationFailure indicates an expected call of LogValidationFailure.
func (mr *MockCustomerLoggerInterfaceMockRecorder) LogValidationFailure(ctx, operation, errorMsg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogValidationFailure", reflect.TypeOf((*MockCustomerLoggerInterface)(nil).LogValidationFailure), ctx, operation, errorMsg)
}

// MockTransactionProcessingServiceInterface is a mock of TransactionProcessingServiceInterface interface.
type MockTransactionProcessingServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockTransactionProcessingServiceInterfaceMockRecorder
}

// MockTransactionProcessingServiceInterfaceMockRecorder is the mock recorder for MockTransactionProcessingServiceInterface.
type MockTransactionProcessingServiceInterfaceMockRecorder struct {
	mock *MockTransactionProcessingServiceInterface
}

// NewMockTransactionProcessingServiceInterface creates a new mock instance.
func NewMockTransactionProcessingServiceInterface(ctrl *gomock.Controller) *MockTransactionProcessingServiceInterface {
	mock := &MockTransactionProcessingServiceInterface{ctrl: ctrl}
	mock.recorder = &MockTransactionProcessingServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransactionProcessingServiceInterface) EXPECT() *MockTransactionProcessingServiceInterfaceMockRecorder {
	return m.recorder
}

// EnqueueTransaction mocks base method.
func (m *MockTransactionProcessingServiceInterface) EnqueueTransaction(transactionID uuid.UUID, operation string, priority int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnqueueTransaction", transactionID, operation, priority)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnqueueTransaction indicates an expected call of EnqueueTransaction.
func (mr *MockTransactionProcessingServiceInterfaceMockRecorder) EnqueueTransaction(transactionID, operation, priority interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnqueueTransaction", reflect.TypeOf((*MockTransactionProcessingServiceInterface)(nil).EnqueueTransaction), transactionID, operation, priority)
}

// GetQueueMetrics mocks base method.
func (m *MockTransactionProcessingServiceInterface) GetQueueMetrics() (*dto.QueueMetrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetQueueMetrics")
	ret0, _ := ret[0].(*dto.QueueMetrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetQueueMetrics indicates an expected call of GetQueueMetrics.
func (mr *MockTransactionProcessingServiceInterfaceMockRecorder) GetQueueMetrics() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetQueueMetrics", reflect.TypeOf((*MockTransactionProcessingServiceInterface)(nil).GetQueueMetrics))
}

// ProcessQueueItem mocks base method.
func (m *MockTransactionProcessingServiceInterface) ProcessQueueItem(ctx context.Context, queueItem *models.ProcessingQueueItem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessQueueItem", ctx, queueItem)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProcessQueueItem indicates an expected call of ProcessQueueItem.
func (mr *MockTransactionProcessingServiceInterfaceMockRecorder) ProcessQueueItem(ctx, queueItem interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessQueueItem", reflect.TypeOf((*MockTransactionProcessingServiceInterface)(nil).ProcessQueueItem), ctx, queueItem)
}

// StartProcessing mocks base method.
func (m *MockTransactionProcessingServiceInterface) StartProcessing(ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "StartProcessing", ctx)
}

// StartProcessing indicates an expected call of StartProcessing.
func (mr *MockTransactionProcessingServiceInterfaceMockRecorder) StartProcessing(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartProcessing", reflect.TypeOf((*MockTransactionProcessingServiceInterface)(nil).StartProcessing), ctx)
}
